getsops/sops

setup.py, sops/__init__.py
=> Fix modification detection in editor mode to use checksums rather than timestamps

examples/all_in_one/.gitignore, examples/all_in_one/README.rst, examples/all_in_one/bin/decrypt-config.sh, examples/all_in_one/bin/edit-config-file.sh, examples/all_in_one/config/secret.enc.json, examples/all_in_one/config/static.py, examples/all_in_one/main.py
This is 1 of 2 PRs for #40. We decided to break them up into separate PRs to prevent overwhelming the reviewer. Although, we should consider a 3rd PR which unifies duplicate content somehow.
In this PR:
- Added `examples/all_in_one` (casing consistent with rest of repo)
- Explanation available in `README.rst`
- https://github.com/twolfson/sops/tree/dev/add.examples.sqwished/examples/all_in_one
=> Added all-in-one example

examples/per_file/.gitignore, examples/per_file/README.rst, examples/per_file/bin/decrypt-config.sh, examples/per_file/bin/edit-config-file.sh, examples/per_file/config.enc/static.py, examples/per_file/config.enc/static_github.json, examples/per_file/main.py
This is the second PR for #40 (complement to #50). In this PR:
- Added per-file example
- Explanation available in `README.rst`
- https://github.com/twolfson/sops/tree/dev/per.file.example.sqwished/examples/per_file
=> Added per-file example

setup.py, sops/__init__.py
=> Split EDITOR parameter, fixes #71

README.md, decrypt.go, main.go, vendor/gopkg.in/urfave/cli.v1/.travis.yml, vendor/gopkg.in/urfave/cli.v1/CHANGELOG.md, vendor/gopkg.in/urfave/cli.v1/LICENSE, vendor/gopkg.in/urfave/cli.v1/README.md, vendor/gopkg.in/urfave/cli.v1/altsrc/flag.go, vendor/gopkg.in/urfave/cli.v1/altsrc/input_source_context.go, vendor/gopkg.in/urfave/cli.v1/altsrc/map_input_source.go, vendor/gopkg.in/urfave/cli.v1/altsrc/yaml_file_loader.go, vendor/gopkg.in/urfave/cli.v1/app.go, vendor/gopkg.in/urfave/cli.v1/appveyor.yml, vendor/gopkg.in/urfave/cli.v1/autocomplete/bash_autocomplete, vendor/gopkg.in/urfave/cli.v1/autocomplete/zsh_autocomplete, vendor/gopkg.in/urfave/cli.v1/category.go, vendor/gopkg.in/urfave/cli.v1/cli.go, vendor/gopkg.in/urfave/cli.v1/command.go, vendor/gopkg.in/urfave/cli.v1/context.go, vendor/gopkg.in/urfave/cli.v1/errors.go, vendor/gopkg.in/urfave/cli.v1/flag.go, vendor/gopkg.in/urfave/cli.v1/funcs.go, vendor/gopkg.in/urfave/cli.v1/help.go
=> go-sops: add cli framework

cmd/sops/main.go, json/store.go, sops.go, yaml/store.go
=> Fixed several issues

README.rst, sops/__init__.py
This appears to work properly. Do you need me to do anything else?
=> Add GPG exec options for #101

cmd/sops/main.go, json/store.go, json/store_test.go
Partially fixes #83. When #100 lands I will add a commit with the example JSON file.
=> Added JSON support

aes/decryptor.go, aes/decryptor_test.go, cmd/sops/main.go, sops.go, sops_test.go
Missing features preventing merge:
=> Editor mode

README.rst, requirements.txt, setup.py, sops/__init__.py
=> add --set flag

aes/decryptor.go, cmd/sops/main.go, json/store.go, kms/keysource.go, pgp/keysource.go, sops.go, yaml/config.go, yaml/store.go
=> Added go.mozilla.org imports

cmd/sops/main.go
Fixes #88 
Example:
```
autrilla@boron /private/tmp $ cat foo.json 
foo: bar
autrilla@boron /private/tmp $ sops --input-type yaml -e foo.json | json_pp
{
"sops" : {
"unencrypted_suffix" : "_unencrypted",
"lastmodified" : "0001-01-01T00:00:00Z",
"mac" : "ENC[AES256_GCM,data:ossq1866uVKFWWNIRAfV2A5roQNjdzjaVQYYgOgApjuhoNZXIPnZS6UzpaH4wpTcGGc9aoCeFEgkhpQyx3+nYdZ8OV5MIDrnKW93x6QtEcNKkTkgT36Q5YTNX8dlHbGBtYdsUDMyynbmVYRTFdO1J7lhuetQ3DA0tQm3ILK25s4=,iv:IbiJsLFTjye/hhsL92JOwOJ00EGyXNXQjpOypxt+114=,tag:Lakkjc38mQl5QrHk2jAVow==,type:str]",
"pgp" : [
{
"enc" : "-----BEGIN PGP MESSAGE-----\n\nwYwDEEVDpnzXnMABBABWsLrcSvVskS8EjLQH8iGmOYSwv0N0AQVqg86mzqOJDaIW\nPVMXdapCFvYri35j0NkoRYw37gG3fxK2163tdEQmpk5+IdeTb1t7HF4SOAWvhxb/\ndL4G66fCHCjjU4MBr4PEgPmqCa1WmCY1roy5mtJfuFGVqcQuA81Ztximx2lCztLg\nAeSQBI9KNXYOm0 …
```
=> Input and output type overrides

cmd/sops/main.go
=> Update version when editing a file

cmd/sops/main.go
=> Fix master keys being overwritten by the last key

aes/decryptor.go, aes/decryptor_test.go
=> Allow decryption of empty values

cmd/sops/main.go, json/store.go, sops.go, yaml/store.go
=> Fix MAC during rotation

sops.go, sops_test.go
=> Fix removing items from slice while iterating

cmd/sops/main.go, sops.go
Extracted input and output handling from each "command" (edit, rotate, encrypt, decrypt).
Output files are only opened if the command was executed successfully.
=> main.go improvements

cmd/sops/main.go, cmd/sops/version.go
=> Update LastModified document timestamp when encrypting

cmd/sops/main.go, json/store.go, sops.go, yaml/store.go
=> Marshal extracted values with the corresponding store

.travis.yml, Makefile, README.rst, make_download_page.sh
Work in progress, do not review or merge yet.
This is intended to fix #166
=> Make packages

cmd/sops/main.go, vendor/github.com/google/shlex/COPYING, vendor/github.com/google/shlex/README, vendor/github.com/google/shlex/shlex.go, vendor/github.com/google/shlex/shlex_test.go
Fixes #210 by parsing $EDITOR like a shell would so sops can pass arguments to the editor.
=> Use shlex to parse $EDITOR

stores/json/store.go
This shows the following:
```
❯ sops -d example.json
Error loading file metadata: SOPS versions higher than 2.0.10 can not automatically decrypt JSON files created with SOPS 1.x. In order to be able to decrypt this file, you can either edit it manually and make sure the JSON value under `sops -> version` is a string and not a number, or you can rotate the file with any version of SOPS between 2.0 and 2.0.10
```
=> Show error message when decrypting SOPS1 JSON files

stores/json/store.go, stores/json/store_test.go, stores/stores.go, stores/yaml/store.go, stores/yaml/store_test.go
=> Fix metadata not found returning the wrong error

keyservice/keyservice.go, keyservice/server.go
=> Fix use of unintialized maps in key service

README.rst
Replace `tests` with `pgp`.
BTW, shouldn't it be `gpg`?
=> Fix gpg import statement

vendor/github.com/mozilla-services/yaml/decode.go, vendor/github.com/mozilla-services/yaml/decode_test.go
Update vendored yaml parser
Fixes #300
=> Update yaml parser

README.rst, cmd/sops/main.go, config/config.go, config/config_test.go
=> Adds `unencrypted_suffix` and `encrypted_suffix` to `.sops.yaml`

.travis.yml, Makefile, sops/__init__.py
=> [PYTHON] Fix Travis builds

stores/json/store.go, stores/json/store_test.go
=> Handle escaping in original json

README.rst
Let me know if I'm mistaken
Thanks for the awesome library
=> Note using the python library uses the older impl

setup.py, sops/__init__.py
@autrilla @jvehent if you want to do another Python release :)
=> [PYTHON] Bump to 1.18

README.rst, cmd/sops/main.go, config/config.go, keyservice/keyservice.go, keyservice/keyservice.pb.go, keyservice/server.go, kms/keysource.go, kms/keysource_test.go, stores/stores.go
Reverts mozilla/sops#416
@marky-mark it looks like your PR broke SOPS assuming roles when not specifying a profile.
=> Revert "AWS Profile"

.travis.yml, README.rst, cmd/sops/common/common.go, cmd/sops/decrypt.go, cmd/sops/edit.go, cmd/sops/encrypt.go, cmd/sops/main.go, cmd/sops/rotate.go, cmd/sops/set.go, functional-tests/src/lib.rs, keyservice/server.go, keyservice/server_test.go, version/version.go
Includes:
* Bug fix
* Regression unit tests
* AWS KMS Functional tests (including a regression test)
* Autofix support within `rotate`, `edit`, `set`, and `decrypt` commands
=> KMS Encryption Context bug fix, autofix, and additional testing

LICENSE
Need License to get into https://github.com/avelino/awesome-go
- Follow the PR: https://github.com/avelino/awesome-go/pull/2603
=> add Mozilla Public License Version 2.0

cmd/sops/common/common.go, cmd/sops/rotate.go, decrypt/example_test.go, keyservice/server_test.go, shamir/shamir.go, stores/dotenv/store.go, stores/dotenv/store_test.go, stores/flatten_test.go
Trying to get featured in https://github.com/avelino/awesome-go
The repo's maintainer has asked we take a look at our [go report card topics](https://goreportcard.com/report/github.com/mozilla-services/sops)
I've remediated all entries which do not require a significant change of code, it is mostly just the addition of comments to exported functions.
=> Fix linting and formatting issues

aes/cipher.go, audit/audit.go, azkv/keysource.go, azkv/keysource_test.go, cmd/sops/common/common.go, cmd/sops/rotate.go, cmd/sops/subcommand/publish/publish.go, cmd/sops/subcommand/updatekeys/updatekeys.go, logging/logging.go, publish/gcs.go, publish/publish.go, publish/s3.go, shamir/shamir.go, shamir/shamir_test.go, sops.go, stores/dotenv/store.go, stores/flatten.go, stores/ini/store.go, stores/json/store.go, stores/stores.go, stores/yaml/store.go, version/version.go
Follow up PR for https://github.com/mozilla/sops/pull/490
and once again:
This is also a step forward in getting sops in avelino/awesome-go
https://github.com/avelino/awesome-go/pull/2603
=> Address Go Lint messages

cmd/sops/main.go
=> Return non-zero exit code for invalid CLI flags

config/config.go, config/config_test.go
Added support to the key group configuration to support AzureKV. It was added to the keyGroup struct but never used.
=> Adding support for azure keyvault to key group config.

cmd/sops/edit.go
this patch fix windows issue #424
=> fix path handling on edit.go for windows

sops.go
=> Fixed typo in GoDoc package description

README.rst
Add note about mandatory keys rotation when using --add-* options.
Covers and Fixes #550
=> document updatekeys command

README.rst
code is calling URLS https://github.com/mozilla/sops/blob/14a22d7a7060a0fba06c5dd716898d47728f0fce/cmd/sops/main.go#L371
=> correct azure key environment in readme

cmd/sops/main.go, cmd/sops/subcommand/exec/exec.go, cmd/sops/subcommand/exec/exec_unix.go
=> Run go fmt on project

Makefile
To fix https://github.com/mozilla/sops/issues/580
=> Fix fpm commands and PROJECT var in Makefile

cmd/sops/main.go, cmd/sops/subcommand/exec/exec.go
now returning exit code with exec-env and exec-file
=> Fixes #626 return exit code with exec-env and exec-file

README.rst
=> #664 remove outdated contact info

cmd/sops/main.go, cmd/sops/subcommand/updatekeys/updatekeys.go, config/config.go
Per suggestion in https://github.com/mozilla/sops/pull/662#pullrequestreview-400292956
=> Rename LoadForFile to LoadCreationRuleForFile

CHANGELOG.rst, version/version.go
Bump version and add changelog for 3.6.1
=> Prep for 3.6.1 release

CODE_OF_CONDUCT.md, DCO
This naturally needs to flow into `master` given the current way branches are setup.
https://github.com/getsops/community/issues/2
https://github.com/getsops/community/issues/3
=> Add DCO and CoC

cmd/sops/edit.go
=> cmd/edit: close temp file before invoking editor

CHANGELOG.rst
Change MarkDown-style formatting to proper RST formatting.
=> Fix CHANGELOG.rst formatting

pgp/keysource.go, pgp/keysource_test.go
=> pgp: improve handling of GnuPG home dir

stores/json/store.go, stores/json/store_test.go
Ref: https://github.com/getsops/sops/pull/1203#discussion_r1327961414
=> Handle return values of dec.Token() to improve error messages

cmd/sops/main.go
=> Report key rotation errors

cmd/sops/main.go
Ref: https://github.com/getsops/sops/pull/1387#issuecomment-1869393332
=> Warn if more than one command is used

Makefile
Upgrading instructions: https://goreleaser.com/blog/goreleaser-v2/#upgrading
Ref: #1524
=> Adjust Makefile to new goreleaser 6.0.0 release

sops.go
Keys (not values) in cleartext.
=> Update sops.go comment

cmd/sops/main.go
=> Allow edit subcommand to create files

.github/dependabot.yaml
This was originally part of #1530 until it got removed from that PR.
=> Dependabot: fix config for Docker, add config for Rust/Cargo

config/config.go
This removes the issues mentioned in #1683.
@felixfontein Can we label this for the next feature release due to the change to the error message? (I don't know how to do this)
=> fix(config): remove unused variables and align error casing

CHANGELOG.rst, version/version.go
Currently includes #1723, will rebase once that is merged.
Ref: https://github.com/getsops/sops/blob/main/docs/release.md#release
=> Release 3.9.3

CHANGELOG.rst, version/version.go
Add changelog and bump version to 3.9.4.
I'd like to wait a bit with finishing this (say, like a day) to see whether #1737 leads to something fixable, so I'm marking it as a draft.
=> Release 3.9.4

pgp/keysource.go
Ref: https://github.com/getsops/sops/issues/896#issuecomment-2688079300
=> Check GnuPG decryption result for non-empty size

cmd/sops/main.go
=> Support --config option in publish subcommand

.git-blame-ignore-revs, cmd/sops/main.go, cmd/sops/subcommand/exec/exec_unix.go, config/config_test.go, publish/vault.go, shamir/shamir.go, sops_test.go, stores/flatten.go
This is mostly indentation / alignment.
=> Run 'gofmt -w' on all .go files

.goreleaser.yaml, CHANGELOG.md
Support multiple architectures for Windows release using goreleaser
=> Added support for multiarch windows release binaries

.github/workflows/release.yml
=> Use latest 1.24 Go version for release build

azkv/keysource.go, gcpkms/keysource.go, gcpkms/keysource_test.go, hcvault/keysource.go, kms/keysource.go, kms/keysource_test.go, pgp/keysource.go, pgp/keysource_test.go
=> Introduce EncryptContext and DecryptContext for AWS, Azure, GCP, PGP and HashiCorp Vault

cmd/sops/main.go
I think it's time :)
Thank you so much to the maintainers who have kept this project going for so many years. You're doing fantastic work!
=> Update authors in main.go
