getsops/sops

sops/__init__.py

instead of writing a tmpfile, write directly to /dev/stdout

Write directly to stdout for decypt/encrypt

---

README.rst
example.json
example.yaml
sops/__init__.py
tests/test_sops.py

This patch adds a `type` entry in the encrypted `ENC[]` section that allows sops to restore a value to its original type, particularly `int` and `float` types.
r? @relud

Add type perservation support

---

sops/__init__.py
tests/test_sops.py

In #24, we discussed potential solutions for unencrypted values and branches. This PR implements the agreed upon feature (using a key suffix to denote an unencrypted value/branch). In this PR:
- Added tests for encryption and decryption
- We paid attention to make sure the MAC included unencrypted values to prevent their tampering
- Implemented unencrypted values/branches support on encryption/decryption
- Added CLI support for `--unencrypted-suffix`
- Added unencrypted suffix persistence by storing it under `tree['sops']['unencrypted_suffx']`
- Fixes #24 
**Notes:**
We did our best to keep code style consistent but due to the functional design we wound up passing around `unencrypted`/`unencrypted_suffx` around a lot =(
We weren't sure about when to camelCase kwargs vs snake_case kwargs …

Added support for unencrypted values and branches

---

sops/__init__.py

[Resubmitted from a branch from my checkout]
Somewhat related to the issue discussed in https://github.com/mozilla/sops/issues/39. When --input-type is anything other than json/yaml it still tries to load the input as json, which can except. If it does except in some cases `tree` can be initialized as a list instead of a dict.
```
bash-3.2$ cat test.txt
[
]
bash-3.2$ sops --input-type blob --output-type json -e test.txt
Traceback (most recent call last):
File "/usr/local/bin/sops", line 9, in <module>
load_entry_point('sops==1.6', 'console_scripts', 'sops')()
File "/Library/Python/2.7/site-packages/sops/__init__.py", line 194, in main
pgp_fps=pgp_fps)
File "/Library/Python/2.7/site-packages/sops/__init__.py", line 353, in initialize_tree
tree = load_file_into_tree(path, itype)
File …
```

sops --input-type load exception allows tree to be initialized as list, not OrderedDict

---

sops/__init__.py

The non-structured input type default expects data to match this regex in `load_file_into_tree()`:
```
valre = b'(.+)^SOPS=({.+})$'
```
However, the output format in `write_file()` does not add a \n after data, so SOPS is appended to `ENC[]` and causes an error when attempting to decrypt.
Steps to reproduce:
```
bash-3.2$ echo 'This is a textfile' > passwords.txt
bash-3.2$ sops -i -e --output-type blob passwords.txt
please wait while a data encryption key is being generated and stored securely
bash-3.2$ sops -d passwords.txt
PANIC: could not retrieve a key to encrypt/decrypt the tree
bash-3.2$ cat passwords.txt
ENC[AES256_GCM,data:<...>,type:str]SOPS={"attention": "This section contains key material that should only be modified with extra care. See `sops -h`.", "kms": <...>
```
The …

Output format mismatch between format of write_file() and the regex in load_file_into_tree()

---

example.yaml
setup.py
sops/__init__.py

Fixes an annoying bug where booleans of value `false` are lost during encryption.
We already have tests that verify data after a roundtrip of encryption/decryption, so I just added booleans in the test data
r? @relud

Fix encryption of false booleans

---

README.rst
setup.py
sops/__init__.py

This PR adds two things.
First, it ensures that, when creating new files, all master keys requested are available to encrypt the file's data key. `sops` would previously ignore the keys that are requested but not accessible, which is not a deterministic behavior to the user.
Second, it implements a configuration file to be added to sops' managed directory. Similar to `.git`, `sops` will look for a file called `.sops.yaml` backward in the directory tree and use its rules to select master keys to use when creating new files. This is, for now, only used on creation of new files, so we don't pay the cost of recursively looking for the config file for any other call to sops.
@mostlygeek: we discussed this together, maybe you want to comment?
r? @relud

Support for configuration file

---

.travis.yml
README.rst

OSX installation works without fuss if installed using python setup via the method documented at http://docs.python-guide.org/en/latest/starting/install/osx/#doing-it-right

README: change OSX install documentation

---

README.rst
sops/__init__.py
tests/test_sops.py

- user can specify "Encryption Context" to each data key encrypted by KMS
- the Encryption Context can be used to restrict access with KMS Policy
some reference on encryption context added:
http://docs.aws.amazon.com/kms/latest/developerguide/policy-conditions.html
http://docs.aws.amazon.com/kms/latest/developerguide/encryption-context.html

Support AWS KMS Encryption Context

---

aes/decryptor.go

Floats should not have padding zeroes after the decimal point, and booleans should be Titlecase.

Format floats and booleans like the Python version does

---

json/store.go
yaml/store.go

In files coming from old versions of sops, sometimes the PGP or KMS branch in the sops branch of the document (also known as the metadata section) contains invalid master keys, such as null items. For example:
```
sops:
kms:
-
```
Now a warning will be shown and that entry will be skipped, instead of panicking.

Added warning message when PGP/KMS items have invalid format

---

README.rst

Document that sops will wait for the editor process to exit, and that this can cause problems with some GUI editors.

GUI editors in README

---

cmd/sops/main.go

os.Create truncates files. We don't want that.
Fixes #146

Use os.OpenFile instead of os.Create.

---

sops/__init__.py

As described in #119, when we output primitives (i.e. non-dicts/lists) to `stdout` we are receiving a trailing ellipses due to the content being treated as a YAML tree. In this PR:
- Repaired non-dict/list logic to not treat stdout much differently
- Fixes #119

Repaired trailing ellipses when outputting primitive values on stdout

---

cmd/sops/version.go
kms/keysource.go
kms/keysource_test.go

This fixes issue #163, and make toMap() more stable across different runs.

When converting master key to map, store context keys alphabetically sorted

---

json/store.go
json/store_test.go

Also, indent JSON with encoding/json
I found this issue while implementing #174

Correctly encode JSON arrays.

---

cmd/sops/main.go
sops.go

Now an error message like this one is shown:
```
Could not decrypt the data key with any of the master keys:
[GPG]: 1022470DE3F0BC54BC6AB62DE05550BC07FB1A0A:	Reading PGP message failed: openpgp: incorrect key
[GPG]: 85D77543B3D624B63CEA9E6DBC17301B491B3F21:	Reading PGP message failed: openpgp: incorrect key```

Better error message when unable to retrieve data key

---

sops/__init__.py

GPG_EXEC was only being set when run as a CLI tool.
It was not being set when used as a Python library.

Make sure GPG_EXEC is set before running GPG

---

README.rst

Documentation update only. sops is now written on go.

Wording: replace boto3 with aws-sdk-go

---

kms/keysource.go
kms/keysource_test.go
pgp/keysource.go
sops.go

In SOPS 1.x, KMS encryption context was stored as a JSON object, but SOPS 2.0 stored it as a comma-separated list of key/value pairs:
```
$ jq '.sops.kms | .[].context' encrypted-python
{
"a": "b",
"c": "d"
}
> jq '.sops.kms | .[].context' encrypted-go
"a:b,c:d"
```
The two outputs are incompatible with each other and caused a stack trace when reading files encrypted with SOPS 1.x.
This patch restores read and output compatibility with SOPS 1.x.
Fixes #190.
This is the only Go I've ever written, so I can attempt to make any requested changed but I'm also okay with someone else polishing this. :)

Fix KMS encryption context for backwards compatibility with SOPS 1.x

---

cmd/sops/main.go

#211 introduced a regression, which causes the editor to be executed like "$EDITOR $EDITOR".

cmd/main: fix shlex branch of editor parsing

---

aes/decryptor.go
decrypt/decrypt.go

This fixes #220 and fixes #222 by changing the IV size to 96-bits (12 bytes) and using crypto/subtle/ConstantTimeCompare to compare the computed and stored SHA-512 hashes.
NB: The PGP tests are failing for me (before and after these fixes) as go's openpgp seems unable to find the secret key it just imported into the secring. I have no idea why not, as every other pgp software on my machine finds it just fine. I have run the rest of the test suite with no errors.

Fix IV size and constant-time MAC comparison

---

aes/decryptor.go
decrypt/decrypt.go

Reverts mozilla/sops#225
This introduced a regression preventing editing of files created with earlier versions of sops. To reproduce:
```
old_sops foo.yaml
new_sops foo.yaml
```
And `new_sops` panics:
```
panic: cipher: incorrect nonce length given to GCM
goroutine 1 [running]:
crypto/aes.(*gcmAsm).Seal(0xc42029cd80, 0x0, 0x0, 0x0, 0xc420228180, 0x20, 0x21, 0xc420229650, 0x2e, 0x30, ...)
/usr/local/Cellar/go/1.8.1/libexec/src/crypto/aes/aes_gcm.go:100 +0x564
go.mozilla.org/sops/aes.Cipher.Encrypt(0x14cc580, 0xc42021e9c0, 0xc420297800, 0x20, 0x600, 0xc42021e9d0, 0x6, 0x15195c0, 0xc4202282a0, 0xc42008a840, ...)
/Users/autrilla/Projects/go/src/go.mozilla.org/sops/aes/decryptor.go:148 +0x670
go.mozilla.org/sops/aes.(*Cipher).Encrypt(0x183a410, 0x14cc580, 0xc42021e9c0, 0xc420297800, 0x20, …
```

Revert "Fix IV size and constant-time MAC comparison"

---

kms/keysource.go

[issue 214](https://github.com/mozilla/sops/issues/214)
Change to make `createSession` handle the current valid AWS partitions:
* `aws`
* `aws-cn`
* `aws-us-gov`
Previously only `aws` had been hard-coded in the arn check

change: check valid arn partition

---

Makefile
test.sh

Switch to use what https://github.com/codecov/example-go#caveat-multiple-files recommends instead of manually including every package in `Makefile`.

Simplify testing in makefile

---

cmd/sops/main.go

First of all, urfave/cli doesn't print errors unless they're a `cli.ExitError`, which causes some errors to not be shown to the user. I've created a `toExitError` function that converts the error to a `cli.ExitError` if it isn't one.
Secondly, there were some cases of the `err` variable being overwritten by branches in main.go, which caused the error to also not be printed.
Third, the `--config` flag was not being used, and getting the Shamir threshold errored if no `.sops.yaml` config file was found.
Fixes #262

Fix some errors not being shown and erroring when no config file is found

---

pgp/keysource.go
pgp/keysource_test.go

If looking up the PGP key in the pubring fails, SOPS will get the key from `gpg.mozilla.org`.

Support retrieving PGP keys from keyservers

---

.circleci/config.yml
Dockerfile

Also updates the Docker image to include the AWS cli and use a newer version of Go

Use go.mozilla.org package name in CircleCI config

---

cmd/sops/main.go

While working on a tool that uses `sops` under the hood, I noticed that the help text for `--unencrypted-suffix` contained two explanations of the default, one of which actually looked like a prefix. This PR removes the hard coded default string and leans on the one generated by the cli package. 
Old help message:
```
--unencrypted-suffix value               override the unencrypted key suffix. default: unencrypted_ (default: "_unencrypted")
```
New help message:
```
--unencrypted-suffix value               override the unencrypted key suffix. (default: "_unencrypted")
```

Fix typo in help text for unencrypted-suffix

---

config/config.go
config/config_test.go

While working on a tool that uses `sops` under the hood, I accidentally cleared out my `.sops.yaml` file. When I ran `sops` it caused a panic that I traced back to an unchecked nil pointer in the function that loads config files. Here's some sample output: 
```yaml
creation_rules:
```
```
❯ sops -e example.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x15a554a]
goroutine 1 [running]:
go.mozilla.org/sops/config.loadForFileFromBytes(0xc4201d0000, 0x46, 0x246, 0x7fff5fbff488, 0xc, 0x0, 0x0, 0x1726084, 0x1)
/private/tmp/sops-20171011-79678-1wrcwgy/sops-3.0.0/src/go.mozilla.org/sops/config/config.go:112 +0x19a
go.mozilla.org/sops/config.LoadForFile(0xc420019190, 0xa, 0x7fff5fbff488, 0xc, 0x0, 0x0, …
```

Don't dereference a null pointer if the config file is empty

---

pgp/keysource.go

since we encode binary data this is generally a good idea
this commit fixes #278 - now both crypto/openpgp and gpg work in a binary
mode, and we can safely use both interchangeably
(e.g. encrypt with crypto/openpgp, and then decrypt with gpg)

add IsBinary: true to FileHints when encoding with crypto/openpgp

---

stores/json/store.go
stores/json/store_test.go

[`Decoder.Token`](https://golang.org/pkg/encoding/json/#Decoder.Token) returns nil, io.EOF at the input stream.
This caused the output json to have no "data" key for an input containing a number:
```
{
"sops": {
"kms": null,
"gcp_kms": null,
"lastmodified": "2018-01-14T14:51:51Z",
"mac": "ENC[AES256_GCM,data:miI91EH0VGqTY9DuJweV61++dq1LmdBwbU/tkaznCeVo2H7z0vws0FdDJiKUiyCwd+PYkpklinVyGWzxDjgR1yWch+9uU4zFkwSiNwLTdQRitYE9Kwxd37E7+AFmJtZIfIdUZsx/gFP4YZ4Pn2cgVK6n9sNRyaGhR4PyCp7TXT4=,iv:XnyghTNLba1edrVYk8sum38pe736T3L5yGJMmBocDyE=,tag:b3z730u8+hPiNxmg8REFHg==,type:str]",
"pgp": [
{
"created_at": "2018-01-14T14:51:51Z",
"enc": "-----BEGIN PGP MESSAGE-----\n\nwcFMA90gOM45xlRNARAAj8AtDWZakRBpMmqRH3z6F+hIkyt2xpP911MAHpU1e4ma\nNZfUcKJybg2XFbAj40uDSEE1o1+hebU18nzYVwVUiDKBGN5f3rSgAIgtcK8u9JT2\nhRPndP7w …
```

Don't consider io.EOF returned by Decoder.Token as error

---

README.rst

The examples for --set and --extract were based on the Python version, and the command line handling has changed slightly for the Go version.
Fixes #285

Update --set and --extract examples

---

README.rst

I found some confusion on how to use gcp into `.sops.yaml` and I think this small change could help other people trying to use it.

Add gcp example for .sops.yaml file

---

cmd/sops/set.go
sops.go
sops_test.go

The previous approach of truncating the tree was erroneous and it isn't possible to make it work by truncating the tree beforehand anyway because we treat the tree as an immutable data structure, so the whole tree has to be copied and then the appropriate values have to be modified.
Fixes #297

Rewrite set functionality to make it work with nested structures

---

cmd/sops/main.go
gcpkms/keysource.go
kms/keysource.go
logging/logging.go
pgp/keysource.go
sops.go

Sets the default log level to `Warn` unless the `--verbose` path is specified. The `-v` shorthand could not be used due to it already being used by `--version`.
Things that will still log even without the `--verbose` flag:
- Specifying a non-string encryption context for KMS (I don't think this should be silently ignored)
- Unencrypted comments in files
- Providing invalid keyservice URIs
Example without `--verbose`, with both a key I can encrypt with but can't decrypt with, and a key I can encrypt and decrypt with:
```
~/Projects/go/src/go.mozilla.org/sops reduce-logging*
❯ cat <<EOF > foo.yaml
foo: bar
EOF
~/Projects/go/src/go.mozilla.org/sops reduce-logging*
❯ sops -e foo.yaml | tee foo.enc.yaml
foo: ENC[AES256_GCM,data:vhkY,iv:k36Hp3sfDWJPv8MtztigsPrvsH25Yqk79O8lcSvoa6o=,tag:9edQ+/9F/n …
```

Default to Warn log level unless verbose flag is passed

---

.travis.yml

I am using helm-secrets in an alpine container, which calls sops under the hood. Obviously Alpine has uclibc installed, so the dynamically linked binaries against glibc that are published will not work.
Instead I am proposing we statically link the binaries across all platforms for portability.

publish statically-linked binaries

---

cmd/sops/main.go

Current experience when running `sops file.yaml` and exiting without saving anything creates an empty file that throws a `sops metadata not found` error if re-opened with sops.
As a user, I would expect if I didn't save a new file in my editor, then there shouldn't be a file created.
This PR attempts to correct that by just not creating the file if the resulting output from an edit session is empty.

dont create the file if its empty

---

cmd/sops/main.go

For some reason we didn't support manually specifying binary input and output file types from cli args. No longer!

Allow forcing binary input and output types through cli flags

---

cmd/sops/decrypt.go
functional-tests/src/lib.rs

When using --extract with multi-line strings, the behavior doesn't match the docs:
```
~/Projects/go/src/go.mozilla.org/sops extract-string*
❯ sops -d foo.yaml 
hello: |
multi-line
string
~/Projects/go/src/go.mozilla.org/sops extract-string*
❯ sops -d --extract '["hello"]' foo.yaml                    
|
multi-line
string
```
When the output value is already a string, there is no need to pass it through `yaml.MarshalValue`, and doing so will change the result if for example the string contains new lines. This makes it annoying to build shell pipelines using --extract, as you have to pipe it through something that removes yaml formatting.
With this patch:
```
~/Projects/go/src/go.mozilla.org/sops extract-string*
❯ sops -d --extract '["hello"]' foo.yaml
multi-line
string
```

Don't yaml.MarshalValue strings on extract

---

README.rst
config/config.go
config/config_test.go

Firstly, I wanted to express how grateful we are for this tool. It's going to drastically change the way we do secrets management for the better across our engineering org. I was wondering if you think the following change is acceptable?
Currently, the `.sops.yaml` file takes an attribute called `filename_regex`. We've found that title to be a bit misleading as it also supports full directory paths as written.
This PR started out as simply an effort to document how we're currently using it with a test to make sure directory path support isn't later removed. Eventually, I ended up implementing [this comment](https://github.com/mozilla/sops/issues/77#issuecomment-237364812).
So what you see here is adding support for an attribute called `path_regex` that has the same behavior as …

deprecate filename_regex in favor of path_regex

---

README.rst
cmd/sops/codes/codes.go
cmd/sops/edit.go
cmd/sops/encrypt.go
cmd/sops/main.go
pgp/keysource.go
sops.go
sops_test.go
stores/stores.go

Answers issue #81.
I've also found the need for encrypted-suffix where we have only a few secrets in a rather large yaml file.
I have run both `make test` and `make functional-tests` and they pass.

Added an --encrypted-suffix option

---

cmd/sops/main.go
cmd/sops/subcommand/keyservice/keyservice.go
keyservice/server.go

A current attack vector is the key service socket being compromised in some way. This would allow attackers to encrypt and decrypt data using all keys the machine running the key service has access to. In some cases, such as a user sharing their key service socket from their laptop to a remote server, this can be solved by forcing the user to confirm every single received request before responding successfully to it.
The current implementation only prompts the user if encryption/decryption succeeded in the first place. This is vulnerable to timing attacks that would let an attacker know whether a user has access to a given key or not.
Another alternative would be to prompt for every single encryption/decryption attempt, regardless of whether it would succeed or not. In my opinion, this …

Introduce key service flag optionally prompting users on encryption/decryption

---

setup.py

Now that the Python version isn't being actively developed, it'll be nice for consumers of the library to not have conflicts with the pinned sops dependencies.

[PYTHON] Un-pin Python dependencies

---

cmd/sops/common/common.go
cmd/sops/decrypt.go
cmd/sops/edit.go
cmd/sops/encrypt.go
cmd/sops/main.go
cmd/sops/rotate.go
cmd/sops/set.go
cmd/sops/subcommand/groups/add.go
cmd/sops/subcommand/groups/delete.go
cmd/sops/subcommand/updatekeys/updatekeys.go
decrypt/decrypt.go
sops.go
stores/json/store.go
stores/json/store_test.go
stores/yaml/store.go
stores/yaml/store_test.go

Previously the Store interface tried to mimic the Marshaler and Unmarshaler
interfaces. This was a mistake, as it meant Stores had no idea whether the files they
were loading were encrypted or not.
Sort-of-fixes #334, but another bugfix is required to solve that issue "the right way".

Refactor Store interface to reflect operations SOPS performs

---

cmd/sops/main.go

If keyservicecmd returns an error, log it.

---

cmd/sops/encrypt.go
functional-tests/src/lib.rs

The `ensureNoMetadata` function was incorrectly implemented and called
LoadEncryptedFile on the InputStore and checked whether the returned error was
MetadataNotFound or not. In the case where loading the input file as an encrypted
file would fail (e.g. due to syntax errors), it would incorrectly report the file as
having a "sops" branch. When using the binary mode, it would try to load the file as
an encrypted binary file (which is expected to be JSON), which would fail, thus
triggering this error.
Includes a functional test that would have detected this.

Fix double encryption prevention

---

README.rst

Closes #349 
Adding and rotating keys for a specific file, to me, feels like something that should be done in-place by default. While not wanting to enforce that in `sops` itself, I think it would be helpful to document the `-i` flag in the README. I was thoroughly confused as to why `-r` was kicking the updated contents to `stdout` and not modifying the existing file. I thought there was a bug in `sops`, which wasn't the case.
Hopefully this helps clear up any confusion for other new users. Happy to incorporate changes to the content as well.
Thanks!

Update rotation steps to use -i

---

Dockerfile

Currently getting a `user: Current not implemented on linux/amd64` error from https://github.com/mozilla/sops/blob/master/audit/audit.go#L103 within a `mozilla/sop` docker container that has an `/etc/sops/audit.yaml` file.
Per https://github.com/golang/go/issues/14625 - this is caused by disabling `cgo`.
As a follow up, we disable `CGO` for our releases, which makes perfect sense, but will have the same problem.

Explicitly enabled cgo within Dockerfile build

---

requirements.txt
sops/__init__.py

ruamel.yaml 0.15.52 changed `CommentedMap` to no longer subclass `OrderedDict` and 0.15.55 changed `CommentedSeq` to no longer subclass `list`, which broke sops's logic for parsing YAML dicts vs lists.
This patch fixes that by checking `collections.abc.MutableMapping` and `collections.abc.MutableSequence` instead.

[PYTHON] Fix compatibility with ruamel.yaml >= 0.15.52

---

README.rst

This PR is mostly just minor grammar corrections (changing markdown syntax to RST syntax), correcting some visual issues in the GitHub-rendered README page for `sops`
* inline code - double ticks
* bash examples - use `..code` blocks, prepend commands with `$`
* correct some links
* some line-length updates, based on changes
All changes are cosmetic only, no technical corrections made.

Correct RST Syntax in README.rst

---

pgp/keysource.go

Fixes #397 
If `HOME` is undefined `gpgHome()` will return `/.gnupg`. gpg has the same behavior.
```
bash-4.2$ env
HOSTNAME=088550c83cf1
TERM=xterm
OLDPWD=/
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
SHLVL=1
HOME=/
_=/usr/bin/env
bash-4.2$ gpg --import /work/a
gpg: Fatal: can't create directory `//.gnupg': Permission denied
```

Use $HOME instead ~ to find the gnupg directory.

---

Makefile
requirements.txt
setup.py
sops/__init__.py

Previously, `--extract` would fail on Python 3:
```
Traceback (most recent call last):
File "/Users/andy/.virtualenvs/sops-py3/bin/sops", line 11, in <module>
load_entry_point('sops', 'console_scripts', 'sops')()
File "/Users/andy/forks/sops/sops/__init__.py", line 278, in main
write_file(tree, path=dest, filetype=otype)
File "/Users/andy/forks/sops/sops/__init__.py", line 1321, in write_file
sys.stdout.write(tree.encode('utf-8'))
TypeError: write() argument must be str, not bytes
```

[PYTHON] Fix --extract on Python 3

---

examples/per_file/README.rst

rename folder tests to pgp in order to import test key

fix line to import test key

---

README.rst
cmd/sops/common/common.go
cmd/sops/edit.go
cmd/sops/main.go
example.ini
stores/ini/store.go
stores/ini/store_test.go
stores/ini/test_resources/example.json
stores/stores.go

Hi there!
This PR adds support for ini files, in an effort to implement https://github.com/mozilla/sops/issues/70. It looks like https://github.com/mozilla/sops/pull/391 was an attempt to implement ini, but .env is distinct from .ini as far as I can see. For example, .env doesn't support sections.
I've attempted to encode the sops metadata in a way that will be readable in diffs, but this is a bit challenging for ini files since things like arrays aren't really supported.
I'm happy to take any suggestions if something looks off. :)

Added support for ini file store

---

README.rst
cmd/sops/main.go
config/config.go
keyservice/keyservice.go
keyservice/keyservice.pb.go
keyservice/server.go
kms/keysource.go
kms/keysource_test.go
stores/stores.go

closes #422 #389 #416
I added in this part. Would something like this be ok? I tested locally and works for with and without aws_profile. 
```      
config := aws.Config{Region: aws.String(matches[1])}
if key.AwsProfile != "" {
config.Credentials = credentials.NewSharedCredentials("", key.AwsProfile)
}```

AWS Profile fix

---

cmd/sops/edit.go

Command `which vim nano` returns 1 when only nano editor is installed
The solutions is to lookup several times
Also improved error reporting: the old code violated two rules from [Go Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments): "Don't panic" and "Error Strings"

Fixed panic when nano available, but vim is not installed

---

cmd/sops/edit.go

By default on alpine there is just vi (busybox compat).
```
/ # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.9.0
PRETTY_NAME="Alpine Linux v3.9"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
/ # which vim nano vi
/usr/bin/vi
```

Add vi to known editors

---

stores/dotenv/store.go
stores/dotenv/store_test.go

It seems most (all?) dotenv implementations support using `#` for comments, so let's do that.

Add comment support to dotenv store

---

cmd/sops/common/common.go
cmd/sops/edit.go
cmd/sops/main.go
sops.go
stores/dotenv/store.go
stores/ini/store.go
stores/json/store.go
stores/stores.go
stores/yaml/store.go

This also forces `Store` implementations used in the CLI to have an example file.
Adds an example "flat" tree for stores that don't support nested values, and a "simple" tree that doesn't contain fancy values like booleans, arrays, and numbers for stores that only support strings.
Fixes #419

Consolidate example trees

---

README.rst
cmd/sops/main.go
pgp/keysource.go

Add support for the SOPS_GPG_KEYSERVER environment variable to
override the default GPG key server (gpg.mozilla.org).

Add support for custom GPG key servers

---

functional-tests/src/lib.rs

Adds two functional tests that use AWS KMS.
The one using encryption context will flap, therefore I'm pointing this PR at a staging branch we can use to combine this PR, https://github.com/mozilla/sops/pull/435, and an incoming migration path PR.

Initial set of AWS KMS tests

---

keyservice/server.go
keyservice/server_test.go

It turns out that sops doesn't send correct KMS encryption context key-value pairs to KMS service during encryption and decryption operations. If an encryption context contains at least two key-value pairs and more than one unique value among the keys' values, sops will incorrectly call KMS API with an encryption context where all correct keys are present, but they all have the same value. This pull request fixes that and adds a regression test for KMS encryption context handling in `keyservice/server.go`, where the bug occurs. 
Suppose sops is asked to encrypt a new file with the following encryption context.
```
"first key": "first value"
"second key": "second value"
"third key": "third value"
```
In that case, sops sends to KMS an encryption context where every key has exactly the same …

Fix KMS encryption context handling

---

Dockerfile

Cause of our current problems in CircleCI: https://superuser.com/a/1417656
Rather than creating a special fix for debian jessie, seems best to just upgrade to a more recent golang container (which is based off of the newer debian stretch)

Upgrade to golang:1.11 in Dockerfile

---

.travis.yml
Makefile
functional-tests/src/lib.rs

Instead of exiting early, only run the kms tests within the context of
mozilla/sops (and not from forks).

Only run kms functional tests within mozilla/sops

---

README.rst
cmd/sops/main.go

so that `path_regex` can match on the full path. It will fix issue https://github.com/mozilla/sops/issues/465

expand file path to full path before processing

---

.travis.yml
CONTRIBUTING.md
README.rst

* Fixes integration tests in travis to not run on PR's (they will now
run on merges into `develop` and `master`)
* Change README.rst and CONTRIBUTING.md to reflect the use of `develop`
as the primary development branch

Changes to travis config and docs for using develop

---

.circleci/config.yml
.travis.yml
CONTRIBUTING.md
Dockerfile
README.rst

Golang 1.12 is the latest and should be sufficiently backwards-compatible.

use golang 1.12 for building sops

---

pgp/keysource.go

Make sure the key fingerprint is longer than 16 characters before
slicing it.
Closes #463

pgp/keysource: Check size of key fingerprint

---

cmd/sops/main.go
functional-tests/src/lib.rs

Adds back support for string values in --set, while retaining support
for yaml multidoc that caused this bug.
Fixes #461

Allow set "json value" to be a string.

---

CHANGELOG.rst
version/version.go

Changelog and `Version` bump for releasing 3.3.1
Would be good to get the change to using `develop` out.

Bump to 3.3.1

---

README.rst
cmd/sops/edit.go
cmd/sops/encrypt.go
cmd/sops/main.go
config/config.go
config/config_test.go
sops.go
sops_test.go
stores/stores.go

Our team would like to use sops to protect kubernetes secrets in YAML files.
Here's what we want to do:
- encrypt all secret literals, regardless of whether they are under the "data" or "stringData" keys
- *not* encrypt any other values in the file, so we can still easily visually scan the encrypted files (so for instance, we could see the unencrypted secret names in a git diff)
- *not* require developers to put any kind of suffix onto key names
- *not* require any additional pre- or post-processors; we want to use `sops decrypt` and pipe straight to `kubectl apply`.
Here's what we've tried:
- without using encrypted suffix, all values will be encrypted, which makes it impossible to visually scan an encrypted YAML file for fields like metadata.name
- you can add an encrypted suffix like …

added encrypted-regex option

---

.travis.yml
README.rst
config/config.go
config/config_test.go
functional-tests/.sops.yaml
functional-tests/src/lib.rs
publish/vault.go

Adds support for publishing to vault using KV v1 and a different mount name (or multiple).
Also further expands the "destination rule config" unit tests.
Supporting kv v1 and a different mount name came back to me from user testing of `sops publish`.

vault kv version and mount names in publish config

---

README.rst
cmd/sops/main.go
cmd/sops/subcommand/exec/exec.go

Hi there, I'm looking at using sops for an infrastructure project. My current use-case looks something like this:
1. Create an AWS EC2 instance with an IAM instance profile that lets it talk to KMS and is pre-loaded with secrets encrypted by sops
2. At boot, the instance executes sops to decrypt the file and writes it to disk.
3. A daemon that loads this file is started. It uses credentials in this file to connect to a remote database, operate on HMACs, etc.
This daemon can alternatively pull secret values out of its environment, which is where this PR comes in. I would much prefer to pass the credential to this daemon using the environment for a few reasons:
- it's possible to pass the credential without it ever touching the disk in plaintext
- it separates the secret encrypted values …

Add an --exec flag to pass decrypted secrets via environment variables to a child process

---

README.rst

Seems like a typo. The old example leaves the whole file unencrypted.

fix --encrypted-regex documentation

---

README.rst

Adds some short documentation about _stdin_, addressing https://github.com/mozilla/sops/issues/330#issuecomment-381687801 and one of the items in #337.

Document how to operate on stdin

---

kms/keysource.go

From official docs for --role-session-name (https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html):
> The regex used to validate this parameter is a string of characters consisting of upper- and lower-case alphanumeric characters with no spaces. You can also include underscores or any of the following characters: =,.@-
This fixes #441, which occurs when the hostname includes spaces and parentheses

Sanitize hostname used for AWS STS role session name

---

README.rst
cmd/sops/main.go
cmd/sops/subcommand/publish/publish.go
config/config.go
publish/vault.go

Hello.
This PR contains 3 changes in 3 corresponding commits:
- implement -recurse cmd option for directory walking for publish command, so you can publish a bunch of files, preserving structure;
- implement -omit-extensions cmd option to omit file extension in destination secret path. Can be specified in .sops.yaml;
- implement pre-check for already existing Vault secret, to avoid version increment if data not changed.

Publishing improvements: directory walking; prevent Vault unneeded version increment

---

.circleci/config.yml

This change accesses the environment variable CIRCLE_TAG to address #542 
Changes:
1. Break docker push into its own job, runs only on tag creation
2. Use machine executor for docker push job (a little faster since it avoids shipping docker context around)
3. use the CIRCLE_TAG variable provided on tag builds
Options:
1. We can merge jobs back AND/OR
2. We can still publish SHA on master and just AMJOR/MINOR/PATCH, etc on tags
I ran in my own circle spae to test tagging.  I obviously dont have your docker creds, so the push fails, but the tagging works.
Run:
``` bash
#!/bin/bash -eo pipefail
docker tag mozilla/sops "mozilla/sops:$CIRCLE_SHA1"
echo "Tag mozilla/sops:$MAJOR"
docker tag mozilla/sops "mozilla/sops:$MAJOR"
echo "Tag mozilla/sops:$MAJOR.$MINOR"
docker tag mozilla/sops …
```

Added version to docker tag #542

---

stores/dotenv/store.go
stores/dotenv/store_test.go
stores/stores.go

When reading and writing dotenv files, we need to make sure to encode/decode newline characters. SOPS does not currently do this, as can be seen below:
```console
$ echo '{"foo": "foo\nbar\nbaz"}' > plaintext.json
$ sops -e --output ciphertext.json plaintext.json
$ sops -d --output-type dotenv ciphertext.json
foo=foo
bar
baz
```
This output is invalid and cannot even be fed back into SOPS:
```console
$ sops -d --output-type dotenv --output plaintext.env ciphertext.json
$ sops -e plaintext.env
Error unmarshalling file: invalid dotenv input line: bar
```
This commit fixes the issue, such that the final `sops -d ...` command above produces the correct output:
```console
$ sops -d --output-type dotenv ciphertext.json
foo=foo\nbar\nbaz
```

Fix newline encoding for dotenv store

---

.circleci/config.yml
.dockerignore
Dockerfile.alpine

Replaces #604 .
I want alpine-based docker images for sops, as it's small and easy to use:
* The current image uses 2 GB+:
```
$ docker images mozilla/sops
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
mozilla/sops        latest              6a8e325d2d11        5 weeks ago         2.3GB
```
* The alpine-based image uses only 65MB:
```
$ docker build -t sops -f Dockerfile.alpine .
...
$ docker images sops
REPOSITORY          TAG                 IMAGE ID            CREATED              SIZE
sops                latest              c4f6175388ce        About a minute ago   64.4MB
```
And this pull request also changes `.circleci/config.yml` to deploy alpine based images as `mozilla/sops:3.5.0-alpine` and `mozilla/sops:alpine`.
I believe we don't need …

Alpine-based docker image

---

cmd/sops/subcommand/exec/exec.go
stores/dotenv/parser.go
stores/dotenv/store.go
stores/dotenv/store_test.go

Rationale
=========
The dotenv store as it exists right now performs splitting on newlines to determine where a new key-value pair or comment begins. This works remarkably well, up until you need to handle values that contain newlines.
While I couldn't find an offical dotenv file format spec, I sampled a number of open-source dotenv parsers and it seems that they typically apply the following rules:
Newline handling:
* If a value is unquoted and contains a literal `\n` (`0x5c6e`), it is interpretted literally and NOT converted to an actual newline (`0x0a`).
* If a value is single-quoted and contains a literal `\n` (`0x5c6e`), it is interpretted literally and NOT converted to an actual newline (`0x0a`).
* If a value is double-quoted and contains a literal `\n` (`0x5c6e`), it is converted …

Add standard newline/quoting behavior to dotenv store

---

stores/json/store.go
stores/json/store_test.go

Add support for decoding JSON arrays of arrays by handling, during
slice decoding, when the next token is an array opening. This produces
nested []interface{} slices.
Closes #640.

Add support for decoding JSON arrays of arrays

---

config/config.go
config/config_test.go

This fixes couple of similar issues, one of them a real use-case.
Currently SOPS breaks if .sops.yaml:
- exists but is empty
- contains `creation_rules:` with no defined rules
- contains only `DestinationRules` but no `CreationRules`
- contains no matching `CreationRules`
- contains invalid  `CreationRules`
It should only break in 4th and 5th case. First 3 cases should be treated as if no .sops.yaml was provided. It's best demonstrated by 3rd case when we want to provide KMS/GPG via CLI argument but we want to have `.sops.yaml` file with `DestionationRule` to publish secrets to Vault. This is currently not possible and is fixed in this PR. 
I added tests for all 4 cases. 5th already has a proper test.
Closes #611

Fix #611 - Dont break when config file exists but CreationRules are empty

---

cmd/sops/main.go

The 'updatekeys' subcommand did not check for the config global string flag.
Add that check and if found use it to set configPath.

Fix #671: `updatekeys` checks for config file flag

---

cmd/sops/subcommand/updatekeys/updatekeys.go

"sops updatekeys" is not working the same as when encrypting a file. The
reason is that for "sops --encrypt", the file path is made absolute before
it is compared with the path_regex in the config file. This is not done for
"sops updatekeys", therefore it does not match the correct entry in the
config file when updating keys.

updatekeys: Make file path absolute

---

kms/keysource.go

Possible fix for issue #679 . After building, I am successfully able to run the following:
```bash
sops my-secrets.yaml
AWS_PROFILE=my-account sops my-secrets.yaml
AWS_PROFILE=my-account sops my-secrets.yaml
```

AWS Profile not correctly resolving .aws/config file - #679

---

config/config_test.go
pgp/keysource.go

I wasn't able to write tests for it, because for this problem to occur, I had to produce a slightly inconsistent state 
with private keys. I guess this only occurs if some old private key (GPG 1?) are migrated to GPG 2.
But this is only guessing.
Nevertheless I was able to test it locally with my GPG key, which produced this problem, before I fixed it.

Fix endless loop in x/crypto/openpgp func ReadMessage

---

cmd/sops/edit.go

This PR closes https://github.com/mozilla/sops/issues/624
Windows will not allow for deletion of a file that has an open handle. 
Close tmpfile after writing to prevent unencrypted tmpfiles out-living
the execution of sops.

Close tmpfile after writing

---

cmd/sops/main.go

This PR resolves https://github.com/mozilla/sops/issues/652, adding support for an `--input-type` argument that will be honored by `sops exec-file`.
Until the argument for `func outputStore` was reversed (to use `input-type` instead of `output-type`) sops kept crashing with the message: 
> Error dumping file: No binary data found in tree
This is certainly a debatable fix, but results were positive.

Support --input-type for exec-file

---

config/config_test.go

Don't include the hostname, just the path. 
Fixes #707 and supersedes #708

Fix vault tests

---

README.rst
cmd/sops/main.go
pgp/keysource.go
pgp/keysource_test.go

* Make use of keys.openpgp.org
* No longer allow for configuring a different keyserver.
Short-term fix for #727 and currently broken builds.

Switch gpg.mozilla.org out for keys.openpgp.org

---

go.mod
go.sum
stores/yaml/store_test.go

Bumps the https://github.com/mozilla-services/yaml version, and adds tests for mozilla-services/yaml#7 and mozilla-services/yaml#8, which fix the problems mentioned in #695.
Fixes #695.

Bump yaml library version; add tests for the issues in #695

---

CHANGELOG.rst
functional-tests/res/comments.enc.yaml
functional-tests/res/comments.yaml
functional-tests/res/comments_unencrypted_comments.yaml
functional-tests/src/lib.rs
go.mod
go.sum
stores/yaml/store_test.go

I couldn't find documentation mentioning that the top-of-document comments are discarded (that needs updating). @autrilla you mentioned that this behavior is documented in https://github.com/mozilla/sops/issues/695#issuecomment-659920093; can you point me to where?
Also, I couldn't run the functional tests since I don't have Rust set up right now, but I guess they'll run in CI :)

Do not discard comments at beginning of YAML documents

---

stores/ini/store.go

The function `encodeMetadataItem` in stores/ini/store.go is not used anywhere, and fails compilation (see #774).
The failure might be Go version dependent (my `go version` says `go version go1.15.6 linux/amd64`), but since the code isn't used, I guess it's best to just remove it.

Remove dead broken code

---

README.rst
cmd/sops/main.go
cmd/sops/subcommand/exec/exec.go
cmd/sops/subcommand/exec/exec_unix.go
cmd/sops/subcommand/exec/exec_windows.go

Some tools (e.g. Terraform) require the right file extension to recognize the file type.
see more details for terraform at https://www.terraform.io/docs/configuration/variables.html#variable-definitions-tfvars-files
i get this error
```sh
~/.go/bin/sops exec-file test.json "terraform plan -var-file={}"
Error: Argument or block definition required
on /tmp/.sops640510710/tmp-file line 1:
1: {
An argument or block definition is required here.
exit status 1
```
works for me:
```sh
~/.go/bin/sops exec-file --filename test.json test.json "terraform plan -var-file={}"
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
...
```

add filename to exec-file

---

age/keysource.go
azkv/keysource.go
decrypt/decrypt.go
gcpkms/keysource.go
hcvault/keysource.go
hcvault/keysource_test.go
kms/keysource.go
pgp/keysource_test.go
shamir/shamir.go
sops.go
version/version.go

* Replaces `%v` formatting of errors using `fmt.Errorf` with `%w`.
* In cases where an `Unwrap` method is not used, `%w` behaves in the _exact_ same way as `%v`.
[Reference:](https://blog.golang.org/go1.13-errors#TOC_3.3.)
> In Go 1.13, the fmt.Errorf function supports a new `%w` verb. When this verb is present, the error returned by `fmt.Errorf` will have an Unwrap method returning the argument of `%w`, which must be an error. In all other ways, `%w` is identical to `%v`.
This would allow returned errors such as this one to check and handle cases when the underlying error is `os.ErrNotExist` using `os.IsNotExist(err)`:
https://github.com/mozilla/sops/blob/8e21de8dbc750f050a54d63209f2f1f93477168c/decrypt/decrypt.go#L21-L24

Add wrap verb to formatted error outputs

---

age/keysource.go
age/keysource_test.go
go.mod
go.sum

Currently the encrypted data key is stored as a binary value, and this
results in SOPS encrypted DOTENV files having weird binary characters.
This changes the encrypt/decrypt methods to use the armor reader writer
provided by: filippo.io/age/armor
Signed-off-by: Andreas Amstutz <tullo@users.noreply.github.com>

Use age/armor for encrypted data key

---

go.mod
go.sum

Fixes #728.
This PR updates SOPS to use the latest version of `aws-sdk-go`, [v1.37.18](https://github.com/aws/aws-sdk-go/releases/tag/v1.37.18).
AWS SSO users can now use SOPS without having to use tools like [aws-vault](https://github.com/99designs/aws-vault).
AWS SSO has been supported by `aws-sdk-go` since [v1.37.0](https://github.com/aws/aws-sdk-go/releases/tag/v1.37.0).

Support AWS SSO authentication

---

config/config.go
config/config_test.go
go.sum

Ref: https://github.com/mozilla/sops/issues/826
This should works. But @sfrevel, if you have better examples so I can complete the tests? (but I guess it could be okay like that already...).

feat: Support more complicated path_regexp (issues/826)

---

README.rst
config/config.go
config/config_test.go

Match file path relative to config file's directory

---

README.rst
config/config.go
config/config_test.go

Reverts mozilla/sops#827. ISTM that PR broke the tests after merging.
cc @bcolucci

Revert "Match file path relative to config file's directory"

---

.github/workflows/cli.yml

If you create a PR against master, and then switch it to being against develop, CI still won't run. You have to push up a new commit to re-trigger it.
As well, would be good to run tests again on merges into master.

Run CI against master as well

---

age/keysource.go
age/keysource_test.go

Fix a bug where settings keys in `.sops.yaml` using YAML’s multiline strings results in  `failed to parse input`:
```
$ cat .sops.yaml
creation_rules:
- path_regex: \.sops\.yaml$
encrypted_regex: ^(data|stringData)$
age: >-
age1XXX,
age1YYY
$ sops foo.sops.yaml
failed to parse input as Bech32-encoded age public key: malformed recipient " age1YYY": invalid character human-readable part: s[0]=32
```

Trim space from age keys

---

README.rst
config/config.go
config/config_test.go

 Match file path relative to config file's directory (2)

---

README.rst

corrected path to keys based on the actual behavior. see [1]
[1]
https://github.com/mozilla/sops/blob/master/age/keysource.go#L108

Correct path to age keys.txt in documentation

---

stores/yaml/store.go
stores/yaml/store_test.go

Prevent comment duplication.

---

pgp/keysource_test.go

* `golang.org/x/crypto/openpgp` requires keys contain identity information.
* A email address can have only a single key with identity information on keys.openpgp.org.
`secops@mozilla.com`, used in keys for unit tests is currently associated to 388B914AFF8BC589962CFA2D996E14AC4DB5EC62: https://keys.openpgp.org/search?q=secops%40mozilla.com
I'm not sure it's permanent one.
The key for `release@mozilla.com` is used for release of FireFox, and I believe we can rely on that's permanent.
https://keys.openpgp.org/search?q=release%40mozilla.com

Use the key of release@mozilla.com for the unit test (#882)

---

hcvault/keysource_test.go

Docker Desktop for OSX has special handling for `localhost` for forwarding traffic to the internal docker VM (specifically for localhost and not `127.0.0.1`). Using `resource.GetHostPort` will return an OS appropriate host and eliminate some the flaky test behavior when running this on other operating systems.

Fix flakey test run on OSX

---

README.rst

The `SOPS_GPG_KEYSERVER` environment variable was removed in pull request #732 (_Switch gpg.mozilla.org out for keys.openpgp.org_). However, a reference to the variable was left in the README as "example" in section 2.13 "_Specify a different GPG key server_".
This pull request removes that part.

Remove SOPS_GPG_KEYSERVER reference in README.rst

---

.circleci/config.yml
.github/workflows/cli.yml
.github/workflows/release.yml
Dockerfile
Dockerfile.alpine
Makefile
go.mod

Upgrade to go 1.17
Will follow this update up with actual library upgrades.
Duplicates:
* #893
* #905
Related:
* #891 - I want to make sure we have completed upgrades before adding in any more new builds
* #911 - same as above

Upgrade to go 1.17

---

age/keysource.go

This removes two pieces of code in the age keysource that are not
actually used.
The `parsedIdentity` is technically a candidate to stay, but should
then be changed to a `[]*age.X25519Identity` type and be lazy-loaded
by `Decrypt` (with the result of `age.ParseIdentities`).

Remove unused age keysource code

---

.github/workflows/cli.yml
.github/workflows/release.yml
pgp/keysource_test.go

- Changes from go 1.13/1.15 to go 1.16
- Adds matrix build and binaries for arm64 (Apple Silicon specifically)

Added support for go 1.17 and darwin-arm64 (Apple Silicon)

---

README.rst
age/keysource.go
age/keysource_test.go

This PR adds support for passing Age keys directly via environment variable `SOPS_AGE_KEY`. This increases ease of use as well as increases security as one can often pass the key directly in memory instead of having to write it to disk first.

Support SOPS_AGE_KEY environment variable

---

.github/workflows/release.yml

Maintain the former no-architecture labeling and include both linux and darwin amd64/arm64 versions in the release

Change labeling and upload linux arm64

---

Makefile
README.rst

* Remove ulfr and autrilla as core maintainers
* Update badges, we no longer us travis-ci
* Remove python docs, especially as it has not been maintained for years
* Fix dev install instructions

README and author tweaks

---

.github/workflows/release.yml
Makefile

I needed the ability to install arm64 based sops in a multi-arch Docker image, thus this PR adds the ability for the release process to generate arm64 .deb and .rpm builds.
May be a bit of an overkill with the Makefile variables, but that could make adding more architectures more DRY in the future.
I'm not a Go or Makefile expert by any stretch, but technically this seems to work, and I've verified this by installing arm64 builds in an arm64 Docker image.
This PR **does not** add arm64 support for sops Dockerhub images.
Fixes #595

Add arm64 .deb and .rpm builds

---

test.sh

`test.sh` stops running as soon as it finds a test failure in a module (so-called fail fast).
Generally speaking, it's not a good idea:
* Developers have to fix tests one by one. They fix a test, run tests again, find a next test failure, fix that, run tests again, find a next test failure...
* Developers cannot see all test results if they don't have complete testing environment. (e.g. consider one without Docker in his/her environment)
* CI doesn't show whether a pull request works correct if some existing test breaks for itself (e.g. #882 )

Tests should not fail fast

---

CHANGELOG.rst
version/version.go

and fix the CHANGELOG's formatting for the last few releases.

prep v3.7.2

---

.github/workflows/release.yml

Previous setup relied implicitly of the correct file to be there. Introduction of arm64 builds broke that implicit assumption.
Fixes #1023

Explicitly build linux amd64 binary

---

Dockerfile.alpine

Building image fails with the following error.
```
$ docker build -t sops -f Dockerfile.alpine .
Sending build context to Docker daemon  884.2kB
Step 1/11 : FROM golang:1.12-alpine3.10 AS builder
---> 6d6865cf688e
builder stage name already used
```

Remove duplicated stage from Dockerfile.alpine

---

stores/yaml/store.go
stores/yaml/store_test.go

Fixes #907
This allows following usage in sops-3.7.x, just like in sops-3.6.x and earlier.
```
echo '{}' | sops --input-type yaml --output-type yaml -e /dev/stdin | sops --input-type yaml --output-type yaml -d /dev/stdin
```

Allow empty maps for yaml (#907)

---

.circleci/config.yml

Docker containers are no longer available in dockerhub since v3.7.0.
It's caused for the alpine version container uses go-1.12 and fails to be built.
It's fixed in #1012.
I want to let CI test building alpine containers so that the problem won't be reproduced.

Build alpine container in CI (#870)

---

.circleci/config.yml

CI failed `make: /bin/sh: Operation not permitted` with after merging #1018.
https://app.circleci.com/pipelines/github/mozilla/sops/135/workflows/9c4d6e8f-f81d-4165-8925-4b69bbe01d41/jobs/438
That's the issue with alpine 3.14 and later: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2
We have to use newer dockerd (20.10.0 or later) to resolve this issue.

Use latest dockerd in CI to allow build alpine image (#870)

---

kms/keysource.go

Originally fixed by @SinisterMinister
Fixes #741
Duplicates #745

Limit role session name length to 64 characters.

---

keyservice/client.go

This allows for easier injection of your own (local) key service server
implementation, in situations where e.g. you do not want to rely on
environment variables or other runtime defaults.
It is not of impact to end-users, but improves the experience of
developers making use of SOPS as an SDK to e.g. provide decryption
services to users. As they will now in many cases end up copying this
bit of code to make this precise change.
xref: https://github.com/fluxcd/kustomize-controller/blob/v0.22.3/internal/sops/keyservice/client.go#L14-L17

keyservice: accept KeyServiceServer in LocalClient

---

cmd/sops/main.go
version/version.go

Adds a new flag `--disable-version-check` which disables the version check (phone home) on `--version`.
I would argue that this behavior should be the default, but for backwards compatibility the other way around is also fine for me. As long as it's possible to turn it off.
Fixes #1100

--version without network request

---

go.mod
go.sum
pgp/keysource.go

[gopass](https://github.com/howeyc/gopass) has been deprecated by the author.
This PR replaces gopass with the term package.

Replace deprecated gopass package with term

---

cmd/sops/main.go
cmd/sops/subcommand/updatekeys/updatekeys.go

Support --input-type for updatekeys

---

.github/workflows/cli.yml
functional-tests/Cargo.toml
functional-tests/src/lib.rs

Bear minimum to get this going again, including an update of
dependencies.
It's worth noting that there is a detachment between the GitHub Action
workflow and running this locally. As there are assumptions around:
1. Having the `pgp/sops_functional_tests_key.asc` imported.
2. Having a Vault server running for two functional tests.
The `functional-tests` Make target does not facilitate this, and
putting something in place using a temporary `GNUPGHOME` and a
container image would likely be a welcome future improvement.
In addition, there is Rust code in `validation/` which appears to be an
artifact from an ancient Python library[1][2]. This should probably be
removed in the future.
[1]: https://github.com/getsops/sops/tree/python-sops
[2]: https://pypi.org/project/sops/

Update rustc functional tests to v1.70.0

---

.github/workflows/cli.yml
.github/workflows/release.yml
Dockerfile
Dockerfile.alpine
go.mod

This updates Go used for builds to 1.20, and updates a forgotten Alpine 3.15 version in a `Dockerfile` to 3.18.

build: update Go to 1.20

---

.github/workflows/cli.yml

As `master` and `develop` are being laid to rest.
Part of #1238 and https://github.com/getsops/community/issues/16

build: run CLI workflow on `main`

---

gcpkms/keysource.go

By addressing the bug in the introduced logic around the `GOOGLE_CREDENTIALS` environment variable.
The variable is now only taken into account when set, and actually containing a value.
Supersedes #1155
Fixes #1151

gcpkms: allow use of Google default credentials

---

age/keysource.go
gcpkms/keysource.go
hcvault/keysource.go
kms/keysource.go
pgp/keysource.go

~Attempt to start to move things from `develop` into `master`.~ This PR addresses one issue reported by @ajvb via email.
1. Errors would be reported multiple times in some cases, especially where a loop would happen on e.g. a series of keys. After close inspection of `main` versus `develop`, reverting all `WithError` calls aligns things again to match original UX is the answer.
2. ~Edge-case backwards compatibility issue for GCP key source, cherry-picked from @ajvb's own https://github.com/mozilla/sops/commits/ajvb/fixes.~
Point 2 will be handled separately.

Revert intro of `WithError` for most key sources

---

version/version.go

... otherwise you could get something like the following (here sops is run without network connection available):
```
$ ./sops --version
sops 3.7.3
[warning] failed to retrieve latest version from upstream: Get "https://raw.githubusercontent.com/mozilla/sops/master/version/version.go": dial tcp: lookup raw.githubusercontent.com: Temporary failure in name resolution
[warning] failed to compare current version with latest: Version string empty
(latest)
$
```

Do not report version when upstream check fails

---

sops.go
sops_test.go

fixes #407
with this fix, when adding a new root hierarchy, the existing root entries won't be dropped anymore

fix `set` feature when adding a new root hierarchy

---

stores/dotenv/store.go
stores/dotenv/store_test.go

Fixes https://github.com/mozilla/sops/issues/565 by sorting the parameters as suggested by @autrilla (implementation by @Jdban) 
Built on top of https://github.com/mozilla/sops/pull/575
The test reliably fails if I comment out line 106 `sort.Strings(keys)`

Ensure stable order of SOPS parameters in dotenv file

---

README.rst

Add the option to use age via the .sops.yaml and updated descriptions to match the given code example.

Add documentation on how to use age in .sops.yaml

---

.goreleaser.yaml
go.mod
version/version.go
version/version_test.go

Based on difficulties observed in https://github.com/getsops/sops/issues/1238#issuecomment-1621315939
This changes the logic of parsing the `version.go` file from a certain
branch to instead make use of the GitHub latest release redirect or
API[1] endpoints for checking if `sops` is on the latest version.
Detaching any future release of SOPS from specific file structures
and/or branches, and (theoretically) freeing it from the requirement of
having to bump the version in-code during release (as this is also done
using `-ldflags` during build). Were it not for the fact that we have
to maintain it for backwards compatibility.
[1]: https://docs.github.com/en/free-pro-team@latest/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release

version: rewrite command to use GitHub endpoints

---

CHANGELOG.rst

For "release note", see: https://github.com/getsops/sops/issues/1266
This does not bump the `version.Version` variable, as this is already done by the build process and this release itself is a release candidate. When the `--version` flag in an existing `sops` binary would already make use of the GitHub API, it would not report it as "latest" either.

Prepare v3.8.0-rc.1

---

.github/dependabot.yaml

This enables Dependabot using two groups, one for GitHub Actions and one for Go Modules.
In the future, we may want to split the Go Modules into multiple groups. For example, one for each key source with a misc catch-all group for any other dependency.
xref: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates#grouping-dependabot-version-updates-into-one-pull-request

Enable Dependabot for Docker, GitHub Actions and Go Mod

---

.github/dependabot.yaml
.github/workflows/release.yml
.goreleaser.yaml

This ensures the file name is unique per release, and can be linked by file name to the specific SOPS version it is targeted at.
Based on comment in https://github.com/getsops/sops/issues/1266#issuecomment-1701880681.

release: generate versioned `.intoto.jsonl`

---

pgp/keysource.go
pgp/keysource_test.go

This option actually gives a false impression, as disabling the agent is no longer possible since GnuPG 2.x.
```
--use-agent --no-use-agent This is dummy option. gpg always requires the agent.
```
xref: https://www.gnupg.org/documentation/manuals/gnupg24/gpg.1.html

pgp: remove `DisableAgent` option

---

age/keysource.go
azkv/keysource.go
gcpkms/keysource.go
hcvault/keysource.go
kms/keysource.go
pgp/keysource.go

Replace the logging of failed encryption and decryption attempts from
error to info level.
This to address a regression in which an encryption or decryption
attempt with a series of keys would result in a list of failed attempts
logged to stderr even when the operation itself eventually succeeded.
xref: https://github.com/getsops/sops/discussions/1270#discussioncomment-6883254

keyservices: address logging regression

---

CHANGELOG.rst
version/version.go

Depends on #1283 
Addresses #1266
```
We are extremely happy to introduce this new minor release of SOPS, now a [CNCF](https://cncf.io) Sandbox project under the stewardship of a new [group of maintainers](https://github.com/getsops/community/blob/main/MAINTAINERS.md).
This release involved significant effort in rewriting and enhancing key source implementations, and includes a number of bug fixes which people had been patiently waiting on for a long period of time. In addition, the release process has been built up from scratch, and now now provides enhanced assurance by publishing SBOMs (Software Bill of Materials), [SLSA3 provenance attestations](https://slsa.dev/spec/v0.1/provenance), and a Cosign signed checksums file as release artifacts.
For a comprehensive list of changes, please …
```

Prepare v3.8.0

---

cmd/sops/decrypt.go
stores/json/store.go
stores/json/store_test.go

When the binary store tries to write data and `data` is not there, or `data` is not a string, or zero or multiple tree branches have been provided, there's now a nice error also explaining about `--output-format`. (The only error handled so far was `data` not being there in the first tree branch, but without that `--output-format` hint.)
Fixes #596.

Improve handling of errors when binary store handles bad data

---

age/keysource.go
age/keysource_test.go

On macOS, prefer XDG_CONFIG_HOME over os.UserConfigDir()

---

cmd/sops/codes/codes.go
cmd/sops/encrypt.go

An empty YAML file results in no tree branch, which trips over encrypt since it assumes there's at least one.
I'm not sure this is the correct way to fix this, since the encrypted result will be empty as well (zero tree branches).
On the other hand, if you encrypt a YAML file with `{}` or `---` in it (and nothing else), there will be at least one tree branch. Decrypting the resulting file yields `{}`. Decrypting an empty file yields an `sops metadata not found` error.

Do not crash if an empty YAML file is encrypted

---

pgp/keysource.go
pgp/keysource_test.go

`make staticcheck` complained about this.

pgp: make error the last return value

---

pgp/keysource.go
pgp/keysource_test.go

I was using `sops` on a qubes machine, with a separate `vault` vm holding the keys. In order to get this to work with sops, the environment override is required. It tripped me up a bit why it didn't accept my override, so this PR adds a warning when an environment override is detected but ignored. 
Successful usage: 
```
$ SOPS_GPG_EXEC=`which qubes-gpg-client-wrapper` go run ./cmd/sops/ --decrypt <my_file>
(works)
```
How it looks during failure:
```
$ SOPS_GPG_EXEC="qubes-gpg-client-wrapper" go run ./cmd/sops/ --decrypt >my_file>
[PGP]    WARN[0000] Environment SOPS_GPG_EXEC was set, but not an absolute path and therefore ignored.  SOPS_GPG_EXEC=qubes-gpg-client-wrapper
[PGP]    WARN[0000] Environment SOPS_GPG_EXEC was set, but not an absolute path and therefore ignored. …
```

pgp: do not require abs path for SopsGpgExecEnv 

---

decrypt/decrypt.go

This picks up a dropped `err` variable in the `decrypt` package.

decrypt: fix dropped error

---

cmd/sops/common/common.go
cmd/sops/main.go
kms/keysource_test.go
pgp/keysource_test.go
stores/yaml/store.go
stores/yaml/store_test.go

Fixes some things reported by `make staticcheck`. This needs more testing and potentially tests, thus I marked it as a draft for now.

Handle errors

---

cmd/sops/main.go

While working on #1317 I noticed that there are quite a few `return err`s which do not use `toExitError()` like most of the other errors that are handled. Some of the errors in questions might already be `cli.ExitError`s, but some might not.

cmd/sops/main.go: make sure to wrap raw errors with toExitError()

---

README.rst

Update README.srt to mention about using environment variables of AWS credentials

Enrich AWS authentication documentation

---

pgp/keysource.go
pgp/keysource_test.go

The error returned by `gpgExec` has just been swallowed. Now it is stringified and returned together with any output to stderr.

Better error reporting for missing gpg binary

---

CONTRIBUTING.md
README.rst
docs/release.md
shamir/README.md

Subset of #1287 that doesn't add linting.
#1272 should be merged first and this PR then updated.

Improve RST and MD files

---

.github/workflows/docs.yml
CONTRIBUTING.md
Makefile

Uses [rstcheck](pypi.org/project/rstcheck/ ) and [markdownlint](https://github.com/markdownlint/markdownlint).
I don't have much experience with markdownlint, but it seems to work well and seems to be useful.

Add linting for RST and MD files

---

README.rst
config/config.go
config/config_test.go
kms/keysource.go
kms/keysource_test.go

A KMS entry in a creation_rule keygroup supports setting aws_profile, but the value is not passed into the KMS MasterKey.
Fixes: #1093

Respect aws_profile from Keygroup Config

---

README.rst
cmd/sops/edit.go
cmd/sops/encrypt.go
cmd/sops/main.go
config/config.go
config/config_test.go
sops.go
sops_test.go
stores/stores.go

Add --mac-only-encrypted to compute MAC only over values which end up encrypted

---

README.rst

Right now the rstcheck test fails because a YAML stream with two documents is labelled as a YAML file.

README: Correctly tag code as yaml-stream

---

hcvault/keysource_test.go

This will overwrite home dir in additional test to ensure local .vault-token is not picked up.

Overwrite home dir in vault test

---

README.rst
cmd/sops/common/common.go
cmd/sops/main.go
cmd/sops/subcommand/updatekeys/updatekeys.go
config/config.go
decrypt/decrypt.go
stores/dotenv/store.go
stores/ini/store.go
stores/json/store.go
stores/json/store_test.go
stores/yaml/store.go
stores/yaml/store_test.go

This PR aims to finish the work started in #930, thanks to @jamesgoodhouse.
I added the use of the Indent param in the store as well as a new `--indent` option in the cli. 
Let me know what you think about it.
Fixes #900, fixes #1048 and fixes #1028

Allow configuration of indentation for YAML and JSON stores

---

pgp/keysource_test.go

On my stock Ubuntu 22.04 machine with Go 1.21 one of the tests fails:
```
--- FAIL: TestGnuPGHome_Validate (0.00s)
--- FAIL: TestGnuPGHome_Validate/wrong_permissions (0.00s)
keysource_test.go:134: 
Error Trace:    /home/xmo/pro/sops/pgp/keysource_test.go:134
Error:          An error is expected but got nil.
Test:           TestGnuPGHome_Validate/wrong_permissions
```
The test assumes that `t.TempDir()` returns a directory with mode `0755`. 
Taking a look at [testing.go:1221 ](https://cs.opensource.google/go/go/+/refs/tags/go1.21.5:src/testing/testing.go;l=1221) shows that this uses [os.MkdirTemp()](https://cs.opensource.google/go/go/+/refs/tags/go1.21.5:src/os/tempfile.go;l=94), which calls `Mkdir(name, 0700)`, causing the test to fail.
To fix this I modified the test to explicitly set …

Fix TestGnuPGHome_Validate

---

README.rst
cmd/sops/main.go

Right now the documenation of the `--indent` option says it's only used for encryption, while it is also used for decryption.
While testing this I noticed that for indenting YAML files, only indents of 2 to 9 are used. If you specify 1, or 10 or larger, the indent is ignored. This comes from go-yaml: https://github.com/go-yaml/yaml/blob/f6f7691b1fdeb513f56608cd2c32c51f8194bf51/emitterc.go#L328-L330
CC @Ph0tonic

Docs: indent is used both for encryption and decryption

---

cmd/sops/main.go

If you execute sops without a config file, you'll get a lovely panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdfa373]
goroutine 1 [running]:
github.com/getsops/sops/v3/cmd/sops/common.newYamlStore(0x0)
/home/tanner/pro/sops/cmd/sops/common/common.go:58 +0x13
github.com/getsops/sops/v3/cmd/sops/common.StoreForFormat(...)
/home/tanner/pro/sops/cmd/sops/common/common.go:162
github.com/getsops/sops/v3/cmd/sops/common.DefaultStoreForPathOrFormat(0x10bf3c2?, {0xc000048090, 0x24}, {0x0?, 0x10c753b?})
/home/tanner/pro/sops/cmd/sops/common/common.go:177 +0x9d
main.inputStore(0xc0001ff340, {0xc000048090, 0x24})
/home/tanner/pro/sops/cmd/sops/main.go:1085 +0x65
main.main.func8(0xc0001ff340) …
```

fix a bug where not having a config results in a panic

---

cmd/sops/main.go

In particular re-adjust line lengths.
Also mention that flags should always come before filenames.

Polish the 'sops help' output a bit

---

cmd/sops/main.go
cmd/sops/subcommand/exec/exec.go

The purpose of this flag is to modify the exec-env's behaviour to only insert decrypted secrets into the environment of the supplied command, without forwarding any of the existing environment variables. 
This is useful in cases where the environment needs to be sanitized from the existing environment variables.
This feature is inspired by [envconsul](https://github.com/hashicorp/envconsul)'s --pristine flag

introduce a --pristine flag to sops exec-env

---

cmd/sops/main.go

Allow to pass multiple paths to the `updatekeys` command, e.g. `sops updatekeys file1 file2 file3`.

Allow to pass multiple paths to 'updatekeys'

---

README.rst
age/keysource.go
azkv/keysource.go
cmd/sops/codes/codes.go
cmd/sops/common/common.go
cmd/sops/decrypt.go
cmd/sops/edit.go
cmd/sops/main.go
cmd/sops/rotate.go
cmd/sops/set.go
cmd/sops/subcommand/groups/add.go
cmd/sops/subcommand/groups/delete.go
cmd/sops/subcommand/publish/publish.go
cmd/sops/subcommand/updatekeys/updatekeys.go
gcpkms/keysource.go
hcvault/keysource.go
keys/keys.go
kms/keysource.go
pgp/keysource.go
sops.go
sops_test.go

This is more generic way to address https://github.com/getsops/sops/issues/305. As suggested in https://github.com/getsops/sops/issues/305#issuecomment-1793766331 and https://github.com/getsops/sops/issues/305#issuecomment-1793768768 it supports `--decryption-order` and **SOPS_DECRYPTION_ORDER** to specify the order in which decryption method are tried. Default order is `age,pgp`, so it covers functionality of #1121 too.
Couple of additional thoughts:
-  Sorting just indices as suggested in https://github.com/getsops/sops/pull/1121#discussion_r1382581918 together with priorities makes code a bit cryptic. Maybe using copy() to clone the group slice and sort the cloned slice could be acceptable alternative (since we don't modify the elements, but only the order)?
- Passing DecryptionOrder …

Sort masterkeys according to decryption-order

---

cmd/sops/main.go

First step for getting rid of `--background`; ref: #629.
The actual removal should only happen a longer time in the future.

Deprecate the --background option to exec-env and exec-file

---

stores/dotenv/store.go
stores/flatten.go
stores/flatten_test.go
stores/ini/store.go

Fixes #857 similarly to #1338.

INI, DotEnv stores: shamir_threshold is an integer

---

cmd/sops/encrypt.go
sops.go
stores/dotenv/store.go
stores/dotenv/store_test.go
stores/ini/store.go
stores/json/store.go
stores/stores.go
stores/yaml/store.go
stores/yaml/store_test.go

Depending on the output store, the keys used for storing SOPS metadata vary. For YAML, JSON, and INI files, the `sops` top-level key is used. For DotEnv files, keys starting with `sops_` are used.
Fixes #1384.

Make check whether file contains invalid keys for encryption dependent on output store

---

cmd/sops/encrypt.go
stores/dotenv/store.go
stores/ini/store.go
stores/json/store.go
stores/stores.go
stores/yaml/store.go

Ref: https://github.com/getsops/sops/pull/1393#discussion_r1438409916

Create a constant for the 'sops' metadata key

---

cmd/sops/edit.go
cmd/sops/encrypt.go
cmd/sops/main.go

Preparation for a rewrite of https://github.com/getsops/sops/pull/1343, which aims at implementing https://github.com/getsops/sops/issues/1333 (Make encrypt, decrypt, rotate, set, and edit proper commands).
This simplifies the main command handler to a more manageable ~180 lines of code, and heavily reduces the copy'n'paste that would happen in an implementation like https://github.com/getsops/sops/pull/1343.
This is #1387 without #974. Once merged I'll update #1387 to contain a version of #974 rebased to the then current `main` branch.

Move extraction of encryption and rotation options to separate functions

---

README.rst
cmd/sops/main.go
examples/all_in_one/README.rst
examples/all_in_one/bin/decrypt-config.sh
examples/per_file/README.rst
examples/per_file/bin/decrypt-config.sh
functional-tests/src/lib.rs

This is another Work in Progress for exploring how to implement #1333, similar to the original WIP #1343. Right now the new subcommands are basically a stripped-down copy'n'paste of the current "main" command. This PR based upon #1389, which reduces the copy'n'paste a lot.
Fixes #1333
~~This PR includes the PRs #1389 and #1390. I will rebase once these are merged.~~

Add separate subcommands for encryption, decryption, rotating, editing, and setting values

---

functional-tests/src/lib.rs

~~Contains a rebased version of #1390.~~

Add basic tests for exec-env and exec-file

---

sops.go

Just came across this typo and fixed it :)

sops: fix typo in interface name

---

cmd/sops/main.go
cmd/sops/subcommand/updatekeys/updatekeys.go

LoadCreationRuleForFile: correctly handle nil without error in callers

---

Makefile

Matching on error messages without specifying locale failed for my German setup
<details>
<summary>Error Message</summary>
```
--- FAIL: TestGnuPGHome_Import (0.02s)                                                                                                                                                                                                                                                                                        
keysource_test.go:71:                                                                                                                                                                                                                                                                                                     
Error Trace: …
```

fix(Makefile): set locale to make tests pass

---

cmd/sops/main.go
cmd/sops/subcommand/exec/exec.go
functional-tests/src/lib.rs

exec-file: if `--filename` is used, use the provided filename without random suffix

---

cmd/sops/main.go

Since the config file loading is only done for backwards compatibility (and the result isn't used), we can simply skip it when only decrypting.
(This is not a problem for new-style decryption - `sops decrypt` subcommand - since that doens't load the config for the file.)
Fixes #868.

Decryption: do not fail if no matching creation_rule is present in config file

---

cmd/sops/main.go
cmd/sops/subcommand/filestatus/filestatus.go
cmd/sops/subcommand/filestatus/filestatus_internal_test.go
functional-tests/res/plainfile.yaml

Closes #460
Add `filestatus` command, reporting if the file is in encrypted or unencrypted state.
I reused `ensureNoMetadata` logic, thus the command would return `0` when the file is not encrypted and `203` when the file is encrypted (respecting the `codes.FileAlreadyEncrypted` error code)
It does not output the error message as returned by `ensureNoMetadata`, preferring a simpler output: "File is encrypted" or "File is unencrypted".
As I'm not so fond on `sops` internals, I'm sure there are multiple things to review, I'll gladly update the code to reflect any suggestion.

add filestatus command

---

README.rst
cmd/sops/main.go
cmd/sops/unset.go
functional-tests/src/lib.rs
sops.go

Add an `unset` command to remove a key or item from the file.
Fixes #1305.
I'm not familiar with Go or Rust, so I mainly adapted what was already present in the `set` command.

add command unset

---

README.rst
cmd/sops/encrypt.go
cmd/sops/main.go
config/config.go
config/config_test.go
sops.go
sops_test.go
stores/stores.go

This PR adds support to annotate comments with a string (e.g., `sops:enc`) which can then be matched with a regex. If it matches, the corresponding value (the one which follows the comment) is encrypted while other values are not. (There is also the opposite regex available, to select those values which should not be encrypted.)
This enables the YAML file to have the same structure encrypted and decrypted, without having to add suffixes or manage complex regexes to match keys. See #543 for more discussion.
~~(This PR currently contains #1389 and will be rebased once that's merged. It is a lot more likely that #1389 will be merged before this PR or any of its variants, so I decided to use that one as a basis.)~~
This PR continues the work of #974 by rebasing #974 upon #1389 and adding some …

Support using comments to select parts to encrypt

---

config/config.go
config/config_test.go

This closes #1123 
The test is not very great (as in: "It doesn't check very much"), but since it was not too hard to implement, I think this is okay.
If you have any comments, please let me know.

Feature: `merge` key for key groups and *make keys unique*

---

CHANGELOG.rst
version/version.go

I've started writing the changelog by going through all PRs merged since 3.8.1, and bumped the version to 3.9.0.
The release process is documented here: https://github.com/getsops/sops/blob/main/docs/release.md

Release 3.9.0

---

.github/workflows/release.yml

Prevent mistakes such as in #1427 and #1527 where this is assumed to be a Go version.
Ref: https://github.com/getsops/sops/issues/1547#issuecomment-2196460328

Explicitly mark goreleaser's version, to avoid confusion with the Go version

---

version/version.go

Right now the code does a HEAD to https://github.com/mozilla/sops/releases/latest and then follows the 301 redirect and does a HEAD to https://github.com/getsops/sops/releases/latest to obtain the version from the 302 redirect that returns.
Since the repo has been renamed, I think we can skip the mozilla/sops step and directly ask getsops/sops.
(The original URL was added in #1261, I'm not sure why we used mozilla/sops there instead of getsops/sops.)

Fix the URL used for determining the latest SOPS version

---

README.rst

Making explicit that only files named `.sops.yaml` will be auto-discovered. And alternative names (like `.sops.yml`) need to be used with the `--config` flag.
Closes #1567

Note on the name of the configuration file

---

Makefile

Why:
* setting the variable SOPS_AGE_KEY_FILE will make tests fail
I also looked at other env variables, but only `SOPS_GPG_EXEC` would cause an issue. I guess keeping this variable could be useful to run tests in a non-standard environment, so I did not include it in the variables to unset.
Fixes https://github.com/getsops/sops/issues/1410

tests: ignore env var SOPS_AGE_KEY_FILE

---

cmd/sops/main.go

The option was renamed while the `updatekeys` subcommand was developed, and the name was not updated in the `updatekeys` PR. See the following for more information: https://github.com/getsops/sops/pull/1509#discussion_r1623288498

updatekeys subcommand: actually use option `--shamir-secret-sharing-threshold`

---

README.rst

Cherry-picked from #1001.
Closes #1001.

Added example of having age recipients in .sops.yaml

---

.github/workflows/linters.yml
functional-tests/src/lib.rs

This PR takes the changes from https://github.com/getsops/sops/pull/1403 and applies them in a dedicated CI workflow.
Fixes https://github.com/getsops/sops/pull/1390

GitHub Actions linter for Rust formatting

---

.github/workflows/cli.yml
.github/workflows/linters.yml
rust-toolchain.toml

Following https://github.com/getsops/sops/pull/1604, we now have two different GH actions requiring a version of Rust.
Rustup allows setting the toolchain version in a file `rust-toolchain.toml`, allowing to set the Rust version once for all Rust commands.

github actions: set rust version globally

---

cmd/sops/main.go

Use `GlobalString` in `loadConfig` since `--config` is not a sub-command flag.
This fixes `--config` being ignored and the CLI erroring out in a maddening way:
```
% sops --config config/sops.yaml encrypt --input-type json --output-type yaml /dev/stdin < data/test.json | head -n 3
config file not found, or has no creation rules, and no keys provided through command line options
% tree
./
├── config/
│   └── sops.yaml
└── data/
└── test.json
3 directories, 2 files
% cat config/sops.yaml
creation_rules:
- path_regex: .*
pgp: ADB6276965590A096004F6D1E114CBAE8FA29165
% cat data/test.json
{
"key": 42
}
%
```
Maybe there is more to this fix, and I am happy to hear about it.
---
FWIW and future reference, here is how I got a debug build on Nix to debug this issue with delve:
```
$ cat …
```

Fix `--config` being ignored by `loadConfig`

---

cmd/sops/main.go

This commit updates the error output by `sops` when failing to operate on a msising file to include the path to the file that was missing.

refactor: specify missing file in error message

---

.github/workflows/release.yml

The Go version for CI is upgraded in #1531, but for the release process we're still using 1.21.x.
Ref: #1572

Build release with Go 1.22.x

---

.github/workflows/docs.yml

Because it has the wrong version there, Dependabot isn't updating the comment.
If you grep for `actions/checkout` in `.github`, you'll see that all other instances have the same image hash, and all of them have `v4.1.7` in their comment.

GHA: fix checkout action version

---

functional-tests/.sops.yaml
functional-tests/src/lib.rs
sops.go

Do not encrypt if a key group is empty, or there are no key groups

---

cmd/sops/common/common.go
cmd/sops/subcommand/updatekeys/updatekeys.go

Inspired by #1509. Also fixes that changes in the Shamir threshold are detected (when the command line flag is used, see #1608).
This does not change the behavior which Shamir threshold is actually used (see the `TODO` comment), that raised the original change in #1509. I'm currently thinking that it should be the user's choice and that should be added as a feature, not a bugfix.

updatekeys subcommand: show changes in shamir_threshold

---

cmd/sops/main.go

Found while playing around with #1613: `sops --config /does/not/exist encrypt foo.sops.yml` resulted in a panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1127533]
goroutine 1 [running]:
github.com/getsops/sops/v3/cmd/sops/common.newYamlStore(0x0)
/path/to/sops/cmd/sops/common/common.go:58 +0x13
github.com/getsops/sops/v3/cmd/sops/common.StoreForFormat(...)
/path/to/sops/cmd/sops/common/common.go:164
github.com/getsops/sops/v3/cmd/sops/common.DefaultStoreForPathOrFormat(0x0, {0xc0001800a0, 0x46}, {0x0?, 0x14974f9?})
/path/to/sops/cmd/sops/common/common.go:179 +0x9d
main.inputStore(0xc00018d4a0, {0xc0001800a0, 0x46})
/path/to/sops/cmd/sops/main.go:2059 +0x65
main.main.func10(0xc00018d4a0) …
```

Do not ignore errors when trying to parse a config file

---

CHANGELOG.rst
version/version.go

Bump version and add changelog.
Ref: https://github.com/getsops/sops/blob/main/docs/release.md#preparation

Release 3.9.1

---

azkv/keysource.go
azkv/keysource_test.go

The Azure Key Vault key parser would fail when URLs contained leading or trailing whitespace, which commonly occurs when using YAML Block Scalar syntax.
```yaml
creation_rules:
- azure_keyvault: >-
https://test.vault.azure.net/keys/test-key/a2a690a4fcc04166b739da342a912c90,
https://test2.vault.azure.net/keys/another-test-key/cf0021e8b743453bae758e7fbf71b60e
```
This resulted in the error:
```bash
could not parse " https://test2.vault.azure.net/keys/another-test-key/cf0021e8b743453bae758e7fbf71b60e" into a valid Azure Key Vault MasterKey
```
- Added `strings.TrimSpace()` to clean the URL before parsing in `NewMasterKeyFromURL()`
- Added test case to verify handling of URLs with leading/trailing spaces

fix(azkv): handle whitespace in Azure Key Vault URLs

---

stores/json/store.go
stores/json/store_test.go

Correctly handle comments during JSON serialization

---

functional-tests/Cargo.toml
functional-tests/src/lib.rs

This is a version of #1530 by @reneleonhardt that squashed the commits and rebased against current `main` to remove the conflicts.
Closes #1530.

Update Rust dependencies

---

CHANGELOG.rst
version/version.go

Once #1688 has been merged, I'd like to create a 3.9.2 release. It contains mostly dependency updates and two bugfixes; see the changelog for details.
Will rebase once #1688 has been merged.
Ref: https://github.com/getsops/sops/blob/main/docs/release.md

Release 3.9.2

---

.github/workflows/cli.yml
.github/workflows/codeql.yml
.github/workflows/docs.yml
.github/workflows/linters.yml
.github/workflows/release.yml

I ran zizmor (https://github.com/woodruffw/zizmor) on our GH actions, the only thing it complained about was missing `persist-credentials: false` for the checkout actions. Since we don't use the credentials later in the workflows (to my knowledge), we should be able to safely add it.

CI: add 'persist-credentials: false' to checkout actions

---

go.mod
go.sum

Dependabot doesn't seem to be able to do this (no idea why), so let's try this manually.

Bump golang.org/x/net to 0.33.0 to address CVE-2024-45338

---

README.rst
pgp/keysource.go
pgp/keysource_test.go

GnuPG: do not incorrectly trim fingerprint in presence of exclamation marks for specfic subkey selection

---

hcvault/keysource_test.go
kms/keysource_test.go

Instead of using images from Docker Hub, use them from the container registry of https://github.com/getsops/ci-container-images.
Fixes #1667

Tests: use container images from https://github.com/getsops/ci-container-images

---

cmd/sops/subcommand/updatekeys/updatekeys.go

An adjusted version of @kleinschrader's #1694 that uses `common.DefaultStoreForPathOrFormat()` instead of basically re-implementing that helper function.
Closes #1694

updatekeys subcommand: fix input-type CLI flag being ignored

---

config/config_test.go
kms/keysource.go
kms/keysource_test.go

Follow-up for #1493, in particular https://github.com/getsops/sops/pull/1493#discussion_r1625318840. Turns out the other fields were important as well.
This not only applies to #1493, but also other operations where `kms.ToString` is used, for example the `rotate` subcommand, the `updatekeys` subcommand, and the `publish` subcommand (the two latter use `DiffKeyGroups`, which relies on `ToString` to identify a full key).
Fixes #1580.

Fix ToString for AWS KMS to include role, context, and profile

---

cmd/sops/main.go

Add --input-type option for filestatus subcommand

---

README.rst
cmd/sops/edit.go
cmd/sops/main.go

Use SOPS_EDITOR before EDITOR

---

cmd/sops/main.go
cmd/sops/set.go
functional-tests/src/lib.rs
sops.go
sops_test.go

Fixes #939.
This uses an extra flag (analogous to the `unset` subcommand) to preserve compatibility, and to avoid all kind of edge cases (input format can be different from output format, for example, in which case not writing the result in general would be a bad idea).

set subcommand: add --idempotent flag that will not write the file if no change happened

---

aes/cipher.go
aes/cipher_test.go
functional-tests/src/lib.rs
sops.go

Implements encryption and decryption of time.Time objects.
Fixes #944.
Closes #1756.

Encrypt and decrypt time.Time objects

---

README.rst

fix(docs): typo in README.rst

---

README.rst
age/keysource.go
age/keysource_test.go
age/ssh_parse.go
age/tui.go
go.mod

Continues #1134.
Closes #1134
Closes #1496
Fixes #692

Add SSH support for age

---

age/keysource_test.go

Fix 
```
--- FAIL: TestMasterKey_Decrypt (0.02s)
--- FAIL: TestMasterKey_Decrypt/loaded_identities (0.00s)
keysource_test.go:254: 
Error Trace:	~/git/github/sops/age/keysource_test.go:254
Error:      	Received unexpected error:
failed to load age identities: failed to parse '~/.config/sops/age/keys.txt' age identities: error at line 1: malformed secret key: separator '1' at invalid position: pos=-1, len=34
Test:       	TestMasterKey_Decrypt/loaded_identities
keysource_test.go:255: 
Error Trace:	~/git/github/sops/age/keysource_test.go:255
Error:      	Not equal: 
expected: string("data")
actual  : []uint8([]byte(nil))
Test:       	TestMasterKey_Decrypt/loaded_identities
--- FAIL: TestMasterKey_Decrypt/invalid_encrypted_key (0.00s)
keysource_test.go:314: 
Error Trace: …
```

make sure that tests do not pick keys.txt from user's HOME dir

---

age/encrypted_keys.go
age/keysource.go
age/tui.go

Another attempt at #1465 without bringing in so much code from [age](https://github.com/FiloSottile/age).
Instead, I created https://github.com/FiloSottile/age/pull/591 upstream to expose `PluginTerminalUI`.
~~- [ ] update `go.mod` once https://github.com/FiloSottile/age/pull/591 is merged~~

feat: add age plugin support

---

age/encrypted_keys.go
age/ssh_parse.go
age/tui.go

Follow-up to #1692 and #1641.
While digging through age's history to figure out why `readPassphrase` vendored in #1692 wasn't there anymore in the latest age version, I noticed that basically readPassphrase was replaced by readSecret in https://github.com/FiloSottile/age/commit/c0e80ef2c985442f957990098ed1cb4b4dd4aa7e. This PR basically does the same, so we can stick to the latest version of cmd/age/tui.go.
Sorry @brianmcgee for the extra work...

vendored age code: consolidate passphrase reading functionality

---

README.rst
cmd/sops/common/common.go
cmd/sops/decrypt.go
cmd/sops/encrypt.go
cmd/sops/main.go
functional-tests/src/lib.rs

Allows to encrypt/decrpyt from stdin by providing no input filename to the `encrpyt` and `decrpyt` commands. For `encrypt`, `--filename-override` must be provided in that case to be able to select the proper creation rule.
Fixes #739
Ref: #1104

Allow to encrypt and decrypt from stdin

---

sops.go

At the end of the function, the key was stored in `m.DataKey`. Since `m` was a copy of the called object, this did not cache anything.
(Also found with `make staticcheck`; I created a separate PR since this is clearly a bugfix.)

Fix caching of Metadata.DataKey

---

cmd/sops/main.go
cmd/sops/subcommand/updatekeys/updatekeys.go

Ref: https://github.com/getsops/sops/pull/1609#discussion_r1763725688
This should end up in a minor or major release, definitely not a bugfix. I'm adding it to the Discussions milestone because of that.

updatekeys subcommand: rename GroupQuorum to ShamirThreshold

---

cmd/sops/main.go

Fixes the issue described in https://github.com/ansible-collections/community.sops/issues/226.
If you are in a subdirectory below `.sops.yaml` (say `subdir/`) and use `sops encrypt local_filename.yaml`, it will correctly match `subdir/local_filename.yaml` in `.sops.yaml` if you're using `path_regex: subdir/local_filename\.yaml`. If you use `sops encrypt --filename-override local_filename.yaml`, it will not find the matching encryption rule since it won't match `/path/to/subdir/local_filename.yaml`, but only `local_filename.yaml`.

If --filename-override is specified, convert it to an absolute path same as regular filenames

---

gcpkms/keysource.go
gcpkms/keysource_test.go
go.mod

Add support for `oauth2.TokenSource` in GCP KMS

---

cmd/sops/main.go
version/version.go

Add option to explicitly check for the latest version; deprecate current default of always doing that unless disabled

---

README.rst
gcpkms/keysource.go
gcpkms/keysource_test.go

We are facing a situation where we want to use short lived access tokens with a minimum of permissions for the kms, and not use static long lived credentials ✨ 
That is why we really want to add support for the use of gcp access tokens in sops using the environment variable ```GOOGLE_OAUTH_ACCESS_TOKEN ``` (also  used by Pulumi/Terrafrom). 
Closes #1188.

Support `GOOGLE_OAUTH_ACCESS_TOKEN` for Google Cloud Platform 

---

CHANGELOG.md
version/version.go

Following the release process: https://github.com/getsops/sops/blob/main/docs/release.md#preparation.
~~The changelog might need an update depending on whether #1578 gets merged in time.~~
Closes #1810.
Closes #1787.

Release 3.10.0

---

CHANGELOG.md
version/version.go

Release 3.10.1

---

stores/yaml/store.go
stores/yaml/store_test.go

This check hid the better (and more general) check in `cmd/sops/encrypt.go` (added in a81f93919c5744fafa180516cea868aa905ebfb0).
The new check was added in adad27e2d4c10d1fb2688bbd3156ef85e1db0735 as part of #1203. I'm not sure why the reserved keyword check was added there, maybe it fixes another thing that the above check does not catch? Do you remember @holiman?
Fixes #1828.

Remove reserved keyword check from YAML store's `LoadPlainFile()`

---

CHANGELOG.md
version/version.go

Following https://github.com/getsops/sops/blob/main/docs/release.md.

Release 3.10.2 release

---

azkv/keysource.go
gcpkms/keysource.go
hcvault/keysource.go
hcvault/keysource_test.go
kms/keysource.go

Allow injecting custom HTTP client for AWS, Azure, GCP and HashiCorp Vault

---

README.rst

Whilst reading the documentation / readme file, I noticed a typo and corrected it.

Fix Typo in README.rst

---

README.rst

The change displays the right path when README.rst is rendered

Correct Windows path to store keys.txt

---

cmd/sops/main.go
functional-tests/src/lib.rs

This allows running "sops set [...]" without leaking secrets in process
listings.
Fixes https://github.com/getsops/sops/issues/729
I'm not a go programmer, please review carefully :-)

Add "--value-file" option to "sops set [...]"

---

stores/flatten.go

Looks like #1394 was inadequate. This fixes it correctly.
Fixes #837.

Fix Shamir threshold encoding for INI and ENV files

---

README.rst

There are a few places where only YAML and JSON were mentioned (next to BINARY).
Fixes #1842.

Fix docs: mention all stores instead of just YAML, JSON, and BINARY

---

age/keysource.go
age/keysource_test.go

Fixes #1843.
Maybe also *all* SSH identities should be loaded, and not the first one found. This needs some more adjustments to the tests, though, since suddenly the Age unit tests depend on all keys of interest in `~/.ssh`. Right now these can be ignored by setting `SOPS_AGE_SSH_PRIVATE_KEY_FILE` accordingly.

Collect age identity loading errors and only report if decryption failed

---

config/config.go
config/config_test.go

Resolves #1864 and resolves #845. Adds Native List as an option for configuring keys in addition to the trailing comma option already given.

Resolves #1864. Adds Native List as an option for configuring keys. 

---

cmd/sops/main.go

Allow to configure --enable-local-keyservice and --keyservice through env variables

---

README.rst
azkv/keysource.go

Firstly: thanks for maintaining such a great tool! It's made my life a lot easier.
Hopefully this PR is helpful in some way; I checked open/closed issues and PRs for something similar being rejected, and couldn't see it.
Anyway, what's the change? I've edited the AZKV implementation to support not including a version in the URL. I.e this makes `https://${VAULT_URL}/keys/${KEY_NAME}/` a valid AZKV URL.
This is a supported behaviour for Azure Key Vault, and is very helpful when it comes to doing rotation of those keys. Updated versions will automatically get fetched by sops for new files with no changes to the config in the repo. This brings AZKV in line with sops' AWS/GCP integrations, which do not require you to specify a key version.
EDIT adding clarification after @felixfontein's …

feat(azkv): Skipping key-version will get latest key

---

README.rst

README: fix argument order

---

README.rst
config/config.go

I ran out of steam and skipped the destination rules for now. (I also never used them, so I'm not the best person to document them :) )
Related: #1767

Start documenting the configuration file format

---

.github/workflows/cli.yml
.github/workflows/release.yml
go.mod

Ref: https://github.com/getsops/sops/pull/1941#discussion_r2338482230
@getsops/maintainers or should we keep Go 1.23 in the matrix?

CI: Build with Go 1.24 and 1.25, release with 1.25

---

cmd/sops/main.go
sops.go
stores/dotenv/store.go
stores/ini/store.go
stores/json/store.go
stores/yaml/store.go

It happened more than once that someone "encrypted" a file using the binary store, which resulted in simply base64 encoding the source since encryption was essentially disabled since some encryption selection option prevented the `data` key to be encrypted.
This PR allows to identify input stores that yield a single key (without comments), and disables all selection options in this case. It also prints warnings for options that potentially disable encryption.
Regarding the warnings: we could also simply not print any warning (might be less annoying to users who simply want to use the same config everywhere), or make the warnings more specific (if they match the `data` key; for that we need to provide the key name as well). @getsops/maintainers what do you think?
Fixes #1822.

Ignore encryption selection options for binary store (and warn when they are used)

---

azkv/keysource.go
azkv/keysource_test.go
config/config.go

Follow-up to #1919.
While working on #1946, I noticed that #1919 did not handle keys specified in key groups (which already have to be split up into their three parts).
CC @daogilvie @r4vi

AZKV: Also allow to omit version for AZKV keys specified in key groups

---

CHANGELOG.md
version/version.go

Release 3.11.0

---

cmd/sops/main.go

These commands were referencing the `decryption-order` option but not actually declaring it as a flag. This commit adds the flag to these commands, allowing users to specify the order in which decryption methods are attempted, just like with "sops -d".

fix: Add decryption-order flag to exec-env, exec-file, and publish commands
